### ISSUE TITLE
找不到http://10.10.10.192/set-dns-to-etcd.sh

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/sextant#101]
为了解决https://github.com/k8sp/auto-install/issues/73

**Comment by pineking** [comment]
cat set-dns-to-etcd.sh
#!/bin/bash

COREOS_PUBLIC_IPV4=$(LC_ALL=C ifconfig | grep 'inet ' | egrep -v '(127\.0\.0\.1)|(10\.1\..*)|(172\.17\..*)'|awk '{print $2}')
HOSTNAME=`hostname`

/usr/bin/etcdctl set /skydns/com/unisound/ailab/"$HOSTNAME" "{\"host\":\"$COREOS_PUBLIC_IPV4\"}"

**Comment by pineking** [comment]
@typhoonzero 这个我来改下吧，提个PR

**Comment by typhoonzero** [comment]
是#73还是本issue?

**Comment by pineking** [comment]
本 issue 我等会看啥#73 讨论的内容

**Comment by typhoonzero** [comment]
赞！

**Comment by pineking** [comment]
如果采用 #102 就不需要 set-dns-tohost了

**Comment by typhoonzero** [comment]
cool，等 https://github.com/k8sp/auto-install/issues/102 关闭之后也关闭这个issue。
