### ISSUE TITLE
dnsmasq 提供 DHCP，DNS，PXE 服务

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#102]
目前使用dhcpd提供dhcp服务，同时，为了获得dhcp的IP和MAC对应关系，使用MAC地址做hostname，然后建立DNS server，通过hostname拿到IP信息。

DNS Server为了获得dhcpd分配的IP和MAC对应关系，需要每个集群节点在获得DHCP 分配的IP后，将本机的IP和MAC（hostname）信息写入etcd，而bootstrapper上的SkyDNS充当DNS Server的角色，向集群提供DNS解析服务，之所以采用SkyDNS，是因为它默认能从etcd里获取IP和hostname信息，默认用etcd做为后端信息存储。

dnsmasq可以同时提供DHCP，DNS，PXE 服务，而且其DHCP和DNS服务内置共享，针对我们的需求，优点是：

1. 不需要每个集群节点在获得IP后向etcd写入IP信息， 而且目前向etcd写入信息只是在开机的时候执行一次，如果在节点在工作状态IP更改，好像并不能立即向etcd更新IP和host信息（我的理解），这个是可能的风险 https://github.com/k8sp/auto-install/issues/103
2. 不需要在bootstrapper再额外搭建skydns提供DNS 服务

**Comment by wangkuiyi** [comment]
我在看 http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq.conf.example 。其中有一段
```
# Give the machine which says its name is "bert" IP address
# 192.168.0.70 and an infinite lease
#dhcp-host=bert,192.168.0.70,infinite
```
一个machine怎么能向DHCP服务说他的名字呢？

**Comment by pineking** [comment]
赞，说明DHCP能拿到hostname

https://wiki.openwrt.org/doc/howto/dhcp.dnsmasq#configuring_dnsmasq_to_associate_client_hostnames_with_dhcp-supplied_ip_addresses

这里也有说明：
The trick is that the DHCP client must send its hostname during the DHCP negotiation. The

dhclient.conf
file, which may be in
/etc/
(debian) or
/etc/dhcp3/
(kubuntu), needs to have a single line uncommented and edited:
send host-name "hostname";
Save the file, then restart the interface. Repeat on all client systems.

我看了下，CentOS7 /var/lib/NetworkManager/dhclient-eno1.conf， Ubuntu 14.04 /etc/dhcp/dhclient.conf 中都有 send host-name

**Comment by wangkuiyi** [comment]
I tried to configure dnsmasq on a VM so to make it a PXE server that
can boot another VM into CoreOS.  Also, I want the dnsmasq VM also
works as a DNS server.

## Create the dnsmasq VM

I started by creating the dnsmasq VM using Vagrant.  I don't create
the VM manually using VirtualBox GUI, because Vagrant allows me to
start a CentOS box easily and quickly.  Here follows the Vagrant file:

```
Vagrant.configure("2") do |config|
  config.vm.define "dnsmasq" do |dnsmasq|
    dnsmasq.vm.box = "centos/7"
    dnsmasq.vm.box_url = "https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box"
    dnsmasq.vm.network "private_network", ip: "192.168.50.4", name: "vboxnet6"
  end
end
```

To start the dnsmasq VM, just type
```
vagrant up dnsmasq
```

On VirtualBox GUI, we can see that this VM has two NICs: `eth0` is a
NAT, which allows us SSH to the VM from the working computer, and
`eth1` is a hostonly NIC, which is connected to a virtual Hub named
`vboxnet6` as specified in above Vagrantfile.


## Configure PXE Service

Now I can SSH to the VM by typing

```
vagrant ssh dnsmasq
```

Then I followed
[this tutorial](http://www.tecmint.com/install-pxe-network-boot-server-in-centos-7/)
to install dnsmasq and tftp-server on this CentOS VM.  I had to
slightly change configuration files listed in the tutorial.

Here is my `/etc/dnsmasq.conf` file:

```
dhcp-range=192.168.50.200,192.168.50.205,12h
# PXE                                                                                                                                                                                 
dhcp-boot=pxelinux.0
# Gateway                                                                                                                                                                             
dhcp-option=3,192.168.50.1
# DNS                                                                                                                                                                                 
dhcp-option=6,192.168.50.1
dhcp-option=6,8.8.8.8
server=8.8.4.4
# Broadcast Address                                                                                                                                                                   
dhcp-option=28,192.168.50.255
# NTP Server                                                                                                                                                                          
dhcp-option=42,0.0.0.0

pxe-prompt="Press F8 for menu.", 60
pxe-service=x86PC, "Install CoreOS from network server 192.168.50.4", pxelinux
enable-tftp
tftp-root=/var/lib/tftpboot
```

Here is my ` /var/lib/tftpboot/pxelinux.cfg/default` file:

```
default coreos

label coreos
  kernel coreos_production_pxe.vmlinuz
  append initrd=coreos_production_pxe_image.cpio.gz cloud-config-url=http://192.168.50.4/install-coreos.sh
```

Also, the aforemented tutorial is for network booting of CentOS.  In
order to boot into CoreOS, I downloaded appropriate boot images and
initramfs image by following
[this tutorial](https://github.com/k8sp/bootstrapper/tree/master/pxe-on-rasppi#deploy-coreos-images).


## Testing PXE Booting

I tried to use Vagrant to create another VM so to test booting from
the dnsmasq VM.  It boots, but it complains about errors dumping the
initramfs image.  So I tried to create a VM using VirtualBox GUI, and
it boots well.

On VirtualBox GUI, I chose to create a VM of 64-bit Oracle Linux.  It
has only one NIC -- a hostonly one connected to `vboxnet6` as the
dnsmasq VM does.

After starting the VM, I pressed F12.  This goes into a booting device
list, where typing `l` boots from PXE server.  Here follows the
screenshot of the booted VM:

<img width="604" alt="vm-booted-from-pxe" src="https://cloud.githubusercontent.com/assets/1548775/17454703/c50694b2-5b54-11e6-87f9-ac22a06fc2a7.png">

We can see that this VM got IP address 192.168.50.201, which is in the
IP range specified in `/etc/dnsmasq.conf` file:

```
dhcp-range=192.168.50.200,192.168.50.205,12h
```

**Comment by pineking** [comment]
目的： 通过 dnsmasq 实现 DHCP和DNS服务
方案：用Vagrant 启动三个 CentOS 7 做测试，一个 server VM，在上面运行dnsmasq，两个 client VMs, client1 和client2

## 创建并启动 Vagrant VMs
1.  server，client1， client2 采用public-network， 三个public-network 桥接在宿主机空闲的eno2的网卡上，实现互通，server使用静态IP 192.168.50.2， client1，clinet2 通过DHCP 获取IP（验证server DHCP 服务）。Vagrantfile如下：

```
config.vm.provider "virtualbox" do |vb|
   vb.gui = false
   vb.memory = "1024"
 end
config.vm.define "server" do |server|•
  #server.vm.network "private_network", ip: "192.168.50.2", name:"vboxnet2"
  server.vm.network "public_network", ip: "192.168.50.2", bridge:"eno2"
  server.vm.hostname = "server"
end

config.vm.define "client1" do |c1|
  c1.vm.network "public_network", type:"dhcp", bridge:"eno2"
  c1.vm.hostname = "client1"
end

config.vm.define "client2" do |c2|
  c2.vm.network "public_network", type:"dhcp", bridge:"eno2"
  c2.vm.hostname = "client2"
end
```

**Comment by pineking** [comment]
> Integration with DHCP.

Dnsmasq reads /etc/hosts so that the names of local machines are available in DNS. This is fine when you give all your local machines static IP addresses which can go in /etc/hosts, but it doesn't work when local machines are configured via DHCP, since the IP address allocated to machine is not fixed. Dnsmasq comes with an integrated DHCP daemon to solve this problem.
The dnsmasq DHCP daemon allocates addresses to hosts on the network and tries to determine their names. If it succeeds it add the name and address pair to the DNS. There are basically two ways to associate a name with a DHCP-configured machine; either the machine knows its name which it gets a DHCP lease, or dnsmasq gives it a name, based on the MAC address of its ethernet card. For the former to work, a machine needs to know its name when it requests a DHCP lease. For dhcpcd, the -h option specifies this. The names may be anything as far as DHCP is concerned, but dnsmasq adds some limitations. By default the names must no have a domain part, ie they must just be a alphanumeric name, without any dots. This is a security feature to stop a machine on your network telling DHCP that its name is "www.microsoft.com" and thereby grabbing traffic which shouldn't go to it. A domain part is only allowed by dnsmasq in DHCP machine names if the domain-suffix option is set, the domain part must match the suffix.

As an aside, make sure not to tell DHCP to set the hostname when it obtains a lease (in dhcpcd that's the -H flag.) This is not reliable since the DHCP server gets the hostname from DNS which in this case is dnsmasq. There is a race condition because the host's name in the DNS may change as a result of it getting a DHCP lease, but this does not propagate before the name is looked up. The net effect may be that the host believes it is called something different to its name in the DNS. To be safe, set the hostname on a machine locally, and pass the same name to DHCP when requesting a lease.

**Comment by wangkuiyi** [comment]
@pineking 无法更赞！

**Comment by LestDou** [comment]
## 实验环境验证Coreos通过cloud-config启动
这里我并没有使用Vagrant的方式验证，而是使用试验环境直接通过dnsmasq引导pxe后，通过cloudconfig生成master/worker的方式进行验证
这里分别启动两个node，分别为 worker0 worker1

### 首先在bootstapper上配置并启动dnsmasq服务：
```
# listen interface
interface=eth0
bind-interfaces
domain=ailabs.baifendian.com
dhcp-range=192.168.2.50,192.168.2.100,255.255.255.0,12h
#Gateway
dhcp-option=3,192.168.2.10
#DNS
dhcp-option=6,192.168.2.10,8.8.8.8

no-hosts
expand-hosts
no-resolv
local=/ailabs.baifendian.com/
domain-needed
# PXE
dhcp-boot=pxelinux.0
# Broadcast Address
dhcp-option=28,192.168.2.255

pxe-prompt="Press F8 for menu.", 60
pxe-service=x86PC, "Install CoreOS from network server 192.168.2.10", pxelinux
enable-tftp
tftp-root=/var/lib/tftpboot
```
引导后通过pxe找到cloud-config安装到磁盘在cloud-config文件中，修改网络的模式为dhcp即可
```
...
hostname: worker0
...
  units:
    - name: 00-eth0.network
      runtime: true 
      content: |
         [Match]
         #Match the interface name
         Name=enp0s25
         [Network]
         DHCP=ipv4
...

```
安装完成后，为经过任何修改操作的效果如下：
###  1. 主机名为 cc中指定的 worker0
```
worker0 core # cat /etc/hostname 
worker0
```
### 2. dnsmasq为这台server分配了一个范围内的ip地址
```
worker0 core # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 68:f7:28:21:4a:02 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.52/24 brd 192.168.2.255 scope global dynamic enp0s25
       valid_lft 40142sec preferred_lft 40142sec
    inet6 fe80::6af7:28ff:fe21:4a02/64 scope link 
       valid_lft forever preferred_lft forever
```
### 3. dnsmasq为server指定了配置文件中的nameserver
```
worker0 core # cat /etc/resolv.conf 
# This file is managed by systemd-resolved(8). Do not edit.
#
# Third party programs must not access this file directly, but
# only through the symlink at /etc/resolv.conf. To manage
# resolv.conf(5) in a different way, replace the symlink by a
# static file or a different symlink.

nameserver 192.168.2.10
nameserver 8.8.8.8
```
### 4. dnsmasq 为server指定了默认网关
```
worker0 core # netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.2.10    0.0.0.0         UG        0 0          0 enp0s25
192.168.2.0     0.0.0.0         255.255.255.0   U         0 0          0 enp0s25
192.168.2.10    0.0.0.0         255.255.255.255 UH        0 0          0 enp0s25
```
### 5.从worker0正向和反向解析
```
worker0 core # nslookup worker0
Server:		192.168.2.10
Address:	192.168.2.10#53

Name:	worker0
Address: 192.168.2.52


worker0 core # nslookup worker1
Server:		192.168.2.10
Address:	192.168.2.10#53

Name:	worker1
Address: 192.168.2.55

worker0 core # nslookup 192.168.2.52
Server:		192.168.2.10
Address:	192.168.2.10#53

52.2.168.192.in-addr.arpa	name = worker0.ailabs.baifendian.com.

worker0 core # nslookup 192.168.2.55
Server:		192.168.2.10
Address:	192.168.2.10#53

55.2.168.192.in-addr.arpa	name = worker1.ailabs.baifendian.com.
```
### 6.从worker1进行同样的验证：
```
worker1 core # nslookup worker1
Server:		192.168.2.10
Address:	192.168.2.10#53

Name:	worker1
Address: 192.168.2.55

worker1 core # nslookup worker0
Server:		192.168.2.10
Address:	192.168.2.10#53

Name:	worker0
Address: 192.168.2.52

worker1 core # nslookup 192.168.2.55
Server:		192.168.2.10
Address:	192.168.2.10#53

55.2.168.192.in-addr.arpa	name = worker1.ailabs.baifendian.com.

worker1 core # nslookup 192.168.2.52
Server:		192.168.2.10
Address:	192.168.2.10#53

52.2.168.192.in-addr.arpa	name = worker0.ailabs.baifendian.com.
```

### 实验结果证实这种方法（dnsmasq）是可以达到我们取代pxe dhcpd dns三个服务的目的的。

**Comment by typhoonzero** [comment]
今天试验的结果是：
使用vagrant启动一个coreos节点，然后使用https://github.com/jpillora/docker-dnsmasq 的docker镜像在coreos上启动dnsmasq服务。并启动nginx服务，和docker registry服务（详细配置方法稍后会更新到auto-install项目）。试验可以达到和上面相同的效果。

这样，初始化一个集群就不需要一台单独的CentOS7服务器，只要先手动安装一台CoreOS机器，并执行bootstraper，就可以将这台机器作为初始化节点（种子节点），其他机器完成自动化配置，而且这台机器上也可以运行k8s的master或worker，比较节省资源。

**Comment by LestDou** [comment]
关于新版bootstrapper启动程序的一些想法：
跟@typhoonzero 讨论之后觉得bootstrapper可以采用docker container的方式来启动
这样做有两个好处：
1. 可以节省资源，不需要单独使用一台物理机
2. 部署更加方便

### 采用docker container所需要的条件：

1. dnsmasq的image
2. nginx server的image
3. pxe所需要的引导文件
4. client装机所需的coreos 镜像
5. kubernetes安装所需要的docker image 和aci

### 基于以上几点，我想到两种实现的方式：

1. bootsrapper和 docker registry 分开两个程序进行部署，先使用一个程序来部署docker registry，并把bootsrapper 所需的 nginx server / ndsmasq image push到registry中，然后再用另一个程序来部署bootsrapper，从registry中获取所需的images。这种方法的好处是耦合性较小，可以分开开发。

2. 把docker registry放到bootsrapper上共同使用一个程序实现部署。这种方法的好处是交付便利而且对于用户而言更加易用。缺点是步骤过多，开发过程中需要考虑更多的异常处理，周期可能会相对较长。

不知道大家有没有什么建议吗
