### ISSUE TITLE
set-dns-to-etcd 服务可能的问题

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#103]
我有个问题：

1. 目前set dns to etcd 服务是不是只是在开机的时候one shot 执行一次，像etcd中写入IP和hostname信息，如果在开机之后，工作状态，IP改变了（有这个可能吗？）set-dns-to-etcd 服务并不会再次执行，导致etcd信息和实际的IP/hostname 信息不一致，有没有发生这种问题这种发生可能性？

如果有问题，https://github.com/k8sp/auto-install/issues/102 方案可不可以解决？

**Comment by jiamliang** [comment]
如果每一次开机都执行一次 set dns to etcd 会有什么问题？

**Comment by typhoonzero** [comment]
按照现在的方式，唯一可能IP变化就是DHCP租约到期了。不考虑有人ssh上去手动修改。 但这里的确需要考虑，在set之前先get下，是否已经有当前IP的信息，如果有的话说明之前肯定有机器的IP发生了变化，只需要覆盖成新的IP／hostname对应即可

**Comment by wangkuiyi** [comment]
请参照 https://github.com/k8sp/auto-install/issues/102 看看可否通过使用 dnsmasq 不再需要每次开机的时候 set-dns-to-etcd 了。

**Comment by typhoonzero** [comment]
已采用dnsmasq方案
