### ISSUE TITLE
用Ceph作为Kubernetes机群的分布式文件系统

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#109]
我们琢磨Ceph有一段时间了。但是从[现存的几个issue看](https://github.com/k8sp/auto-install/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20ceph)，貌似不是所有人对Ceph中的基本概念都理解一致的。

在这里把基本概念梳理一下，把面临的问题列一下，技术讨论总结一下。
## 基本概念

在 Ceph 官方文档页面里 http://docs.ceph.com/docs/hammer/rados/ 介绍了Ceph提供的几个概念：
1. Ceph Storage Cluster = 1+ Ceph MON and 2+ Ceph OSD daemons
   
   > The Ceph Storage Cluster is the foundation for all Ceph deployments. Based upon RADOS, Ceph Storage Clusters consist of two types of daemons: a Ceph OSD Daemon (OSD) stores data as objects on a storage node; and a Ceph Monitor (MON) maintains a master copy of the cluster map. A Ceph Storage Cluster may contain thousands of storage nodes. A minimal system will have at least one Ceph Monitor and two Ceph OSD Daemons for data replication.
2. Ceph Filesystem, Ceph Object Storage 和 Ceph Block Devices 都是访问 Ceph Storage Cluster的方式。
## 访问方式
1. 如果程序是我们自己写的，则可以调用 Ceph Storage Cluster 的标准API：librados 来访问Ceph机群里的文件。librados文档页面里有一个完整的C语言的例子： http://docs.ceph.com/docs/hammer/rados/api/librados/
   
   因为Go程序可以方便地调用C函数，所以上述例子对于Go程序也有用。此外librados还提供C++和Python的 bindings。
2. 如果程序不是我们自己写的，而我们希望这个程序访问Ceph而不是本地文件系统，那么我们需要把Ceph里的目录mount到本地。
   1. 如果程序在 Docker container里执行，那么看上去可以用[Ceph Docker plugin](http://ceph.com/planet/getting-started-with-the-docker-rbd-volume-plugin) 。 关于这个方法的具体讨论在 https://github.com/k8sp/auto-install/issues/84

**Comment by sunxs1101** [comment]
个人理解：
Ceph支持object, block和file storage三种存储方式，Client可以通过RESTful，block和POSIX三种接口分别对这三种存储方式访问，参考http://docs.ceph.com/docs/master/architecture/ 架构图。以块存储为例：

1. 用block接口访问块存储，这种方式是为Host和虚拟机提供服务（[架构图](http://docs.ceph.com/docs/master/architecture/)中的HOST/VM），[参考](http://docs.ceph.com/docs/master/rbd/rbd/)。RADOS Block Devices (RBD)通过[kernel 模块](http://docs.ceph.com/docs/master/rbd/rbd-ko/)或[librbd库](http://docs.ceph.com/docs/master/rbd/qemu-rbd/)与OSDs交互，由[RBD](http://docs.ceph.com/docs/master/rbd/rados-rbd-cmds/)管理RADOS Block Devices(RBD)的镜像。前面comment中的访问方式2应该就属于这种方式，如果在Docker container中运行参考前面comment中的访问方式2。
2. 此外，用户可以不限于这三种接口，利用librados建立自己的接口来对集群访问，用户自己写程序（[架构图](http://docs.ceph.com/docs/master/architecture/)中的APP），程序如何写，参考http://docs.ceph.com/docs/master/rados/api/librados-intro/  即前面comment中的访问方式1。

**Comment by typhoonzero** [comment]
在k8s集群中，存储服务应该至少有2种应用场景：

1. 在docker中以volumn的方式挂载在容器中，应用程序不需要做特殊的修改，直接使用标准POSIX API(open, write, read, close)就可以操作文件
2. 应用程序本身知道自己需要访问一个object存储服务，可以通过ENV拿到ceph的入口地址，通过RESTapi或language binding访问

**Comment by jiamliang** [comment]
[多台物理机挂载同一块RBD引起的问题](https://github.com/k8sp/ceph-rbd/issues/2)：

有三台机器，分别称为16，15,13

1.  按照https://github.com/k8sp/ceph-rbd/blob/master/mount-on-linux-machine.md ，首先创建liuqsrbd0，然后map到16上，格式化，挂载到/mnt/rbd0目录

2. 在16上cd /mnt/rbd0 创建一个a.txt 文件

3. 在15上执行同样操作（除了格式化），挂载到/mnt/rbd0之后，在15上cd /mnt/rbd0能看到a.txt ,然后在此目录创建b.txt，则在16上看不到15上创建的b.txt。但是在15看到的a.txt 只是文件名和16上相同，此时在15修改a.txt 内容并不会反映到16上。在16上修改也不会反映到15上。

4. 在16上创建c.txt，则15上同样也看不到。

5. 在16上创建b.txt ,能正常创建，和15上的b.txt 不冲突，互相独立。

结论：

多台物理机挂载同一块RBD进行读写操作，读写的结果是相互独立。但是如果原来机器或者新的机器再次挂载同一个RBD，所看到的内容是以多台物理机最后一个写操作的为准。而且需要等待一段时间不定。

所以，为了数据安全，只能有一个机器写。而且，B机器写的内容，如果A机器已经在B机器写之前挂载了RBD，则A机器看不到B机器新写的内容，只有B机器写后，A机器再重新挂载才能看到新写的内容。

**Comment by jiamliang** [comment]
[多台物理机挂载同一块RBD引起的问题](https://github.com/k8sp/ceph-rbd/issues/2)：

有三台机器，分别称为16，15,13

1.  按照https://github.com/k8sp/ceph-rbd/blob/master/mount-on-linux-machine.md ，首先创建liuqsrbd0，然后map到16上，格式化，挂载到/mnt/rbd0目录

2. 在16上cd /mnt/rbd0 创建一个a.txt 文件

3. 在15上执行同样操作（除了格式化），挂载到/mnt/rbd0之后，在15上cd /mnt/rbd0能看到a.txt ,然后在此目录创建b.txt，则在16上看不到15上创建的b.txt。但是在15看到的a.txt 只是文件名和16上相同，此时在15修改a.txt 内容并不会反映到16上。在16上修改也不会反映到15上。

4. 在16上创建c.txt，则15上同样也看不到。

5. 在16上创建b.txt ,能正常创建，和15上的b.txt 不冲突，互相独立。

结论：

多台物理机挂载同一块RBD进行读写操作，读写的结果是相互独立。但是如果原来机器或者新的机器再次挂载同一个RBD，所看到的内容是以多台物理机最后一个写操作的为准。而且需要等待一段时间不定。

所以，为了数据安全，只能有一个机器写。而且，B机器写的内容，如果A机器已经在B机器写之前挂载了RBD，则A机器看不到B机器新写的内容，只有B机器写后，A机器再重新挂载才能看到新写的内容。

**Comment by jiamliang** [comment]
在部署GPU集群的时候，自动化安装完成之后，ceph osd 启动失败：
```
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
ptype_tobe_for_name: name = journal
get_dm_uuid: get_dm_uuid /dev/sdc uuid path is /sys/dev/block/8:32/dm/uuid
create_partition: Creating journal partition num 2 size 5120 on /dev/sdc
command_check_call: Running command: /sbin/sgdisk --new=2:0:+5120M --change-name=2:ceph journal --partition-guid=2:d28e6301-92ab-4d24-9209-0a199efda1b1 --typecode=2:45b0969e-9b03-4f30-b4c6-b4b80ceff106 --mbrtogpt -- /dev/sdc
Could not create partition 2 from 10487808 to 20973567
Error encountered; not saving changes.
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4994, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4945, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1774, in main
    Prepare.factory(args).prepare()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1762, in prepare
    self.prepare_locked()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1794, in prepare_locked
    self.data.prepare(self.journal)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2446, in prepare
    self.prepare_device(*to_prepare_list)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2622, in prepare_device
    to_prepare.prepare()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1964, in prepare
    self.prepare_device()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2054, in prepare_device
    num=num)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1522, in create_partition
    self.path,
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 439, in command_check_call
    return subprocess.check_call(arguments)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/sbin/sgdisk', '--new=2:0:+5120M', '--change-name=2:ceph journal', '--partition-guid=2:d28e6301-92ab-4d24-9209-0a199efda1b1', '--typecode=2:45b0969e-9b03-4f30-b4c6-b4b80ceff106', '--mbrtogpt', '--', '/dev/sdc']' returned non-zero exit status 4
```
ceph在对硬盘进行分区的时候出现了问题：
@pineking  给了一个[参考链接](https://github.com/ceph/ceph-docker/tree/master/ceph-releases/jewel/ubuntu/14.04/daemon#zap-a-device)  按照这个操作，问题解决了。

**Comment by typhoonzero** [comment]
Seems this was the same error to https://github.com/k8sp/sextant/issues/317
