### ISSUE TITLE
把bootstrapper server里的程序弄进一个Docker image

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#112]
微信讨论里，我们说到bootstrapper server上得有一个Docker registry服务，这样才能提供Kubernetes机群需要的各种Docker images。 （@LestDou 配置过Docker registry。）

既然如此，是不是应该把我们准备安装在 bootstrapper server上的各种程序，包括dnsmas和nginx，都打包放进一个Docker image，然后push到bootstrapper server上的Docker registry里，并且在bootstrapper server上执行？（ @typhoonzero 尝试了在Docker container里跑dnsmasq来[提供PXE和DNS服务](https://github.com/k8sp/auto-install/issues/102#issuecomment-238577462)。）

如果这样做，貌似就不需要假设bootstrapper server的操作系统——只要是有Docker的机器就行了。而且希望bootstrapper程序变得简单很多。

**Comment by wangkuiyi** [comment]
如果用这个办法，那么在如下假设条件下：

1. 我们有一台可以访问Internet的笔记本电脑；
1. 机群里所有机器，包括bootstrapper server，都不能访问Internet；
1. bootstrapper server能访问apt/yum package repository，可以安装Docker，

Kubernetes机群的安装和部署流程变成下面的样子。

1. 从笔记本ssh到bootstrapper server，按照[Docker 官方指南](https://docs.docker.com/engine/installation/)安装Docker；

1. 在笔记本上从DockerHub.com pull Docker registry image，打包，scp到bootstrapper server然后import：

   ```
   notebook$ docker pull registry 
   notebook$ docker save registry > registry.tar
   notebook$ scp ./registry.tar root@bootstrapper-server:/tmp/
   notebook$ ssh root@bootstrapper-server -c "docker load < /tmp/registry.tar"
  ```

**Comment by typhoonzero** [comment]
@wangkuiyi cool idea。这个dockerimage可能会不小

**Comment by zhengbo0** [comment]
可以提前把registry.tar放到笔记本，直接copy到bootstrapper server,就不需要依赖外网了

**Comment by LestDou** [comment]
@wangkuiyi @typhoonzero 
这个registry和bootstrapper应该是解耦的，bootstrapper的部署和启动不应该依赖于registry
我的想法是我们的部署程序是模块化的，可以并行安装而不是顺序执行相互依赖。

bootstrapper不依赖registry的原因是：dnsmasq和bootsrapper /nginx file server 的镜像，我们可以以tar包的形式打到release包里，在启动的时候load到本地的deamon images中即可。

每个功能模块完成自己的任务，尽量不相互影响，最终的endpoint是多个container的形式作为output。
至于依赖registry的，应该是整个bootstrapper安装完成后，给其它node提供服务的时候，而不是bootstrapper这个程序本身。

计划bootsrapper分为以下几个模块：

1. dnsmasq （用于提供dhcp dns pxe）
2. bootstrapper主程序  （一个webserver， 在pxe后，执行install.sh时，为其生成所需要的cloud-config文件。 我们更倾向于去掉nginx，直接用bootsrapper也提供文件服务器的功能，例如提供install.sh 脚本，和coreos镜像）
3. auto_update  （可选项。 主要用于pxe 安装的coreos版本的自动升级，定期尝试下载新版本的coreos image 并更新到 pxe的 install.sh）
4. registry （用于提供一个内部serve镜像的服务）

**Comment by jiamliang** [comment]
提两点看法：
1. docker registry 需要高可用，所以，把这个放在一个物理机节点上是不是安全可靠？当然，存储可以使用分布式存储。我们云知声之前的讨论是放在k8s里面。
2. bootstrapper 做成一个docker image是一个很不错的想法。在今天的例会上，我们也讨论了一下这种做法怎么做到个性化的问题。

1) 我们总是有一个配置文件（bootstrapper.yaml），并且有一个程序（bootsrapper.go）负责把bootstrapper.yaml 翻译成pxe、dnsmasq 、bootstrapper等等模块的配置文件。
2) 我们需要一个dockerfile，把bootstrapper server 所需的模块组件build成一个docker image，并且可以发布出去。别人就可以使用这个docker image，简单快速的运行起来，提供bootstrap的服务。
3) 对于个性化的问题：我们可以吧这个bootstrapper.yaml的样例，以及各服务模块的模板公布出来。用户可以使用这些模板和配置文件，根据自己的实际情况做相应的调整。调整完之后，不需要再从dockerfile build一个新的docker image。而是在执行docker run/start 的时候 指定一个 -v /etc/bootstrap:/etc/bootstrap 参数，吧bootstrapper server上配置文件所在的路径，挂载到docker container里面对应的路径上。这样就可以低成本进行个性化配置。

**Comment by wangkuiyi** [comment]
@jiamliang 赞同第二点中的提醒。

第一点中的registry按照之前和 @LestDou  @typhoonzero 的讨论，只是部署在bootstrapper server上的，给Kubernetes master/worker node提供镜像的，不是存放各种应用的镜像的。存放各种应用，比如tensorflow，镜像的是假设在Kubernetes上的一个DockerHub服务——这个和我们之前讨论的一致。

**Comment by jiamliang** [comment]
哦，我理解错误了。原来仅仅是为了提供安装k8s使用。

**Comment by pineking** [comment]
bootstrapper主程序 （一个webserver， 在pxe后，执行install.sh时，为其生成所需要的cloud-config文件。 我们更倾向于去掉nginx，直接用bootsrapper也提供文件服务器的功能，例如提供install.sh 脚本，和coreos镜像）

[pineking] 如果 go 程序能提供 nginx的功能，砍掉 nginx 是个不错的建议

特别需要注意：为了让机群里每一台机器都可以访问bootstrapper registry，我们要确保每一台机器都可以通过bootstrapper-server这个域名访问bootstrapper server这台机器。这可以通过cloud-config往每台机器的/etc/hosts里写一行<bootstrapper server ip> bootstrapper-server，也可以通过配置dnsmasq的DNS服务。

[pineking] 建议使用 dnsmqsq实现此功能

**Comment by typhoonzero** [comment]
更新的设计在这里： https://github.com/k8sp/auto-install/pull/115
