### ISSUE TITLE
把dnsmasq binary放进scratch-based Docker image

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#122]

**Comment by wangkuiyi** [comment]
## 实验

尝试把dnsmasq executable binary file放进一个scratch-based Docker image，然后跑起来

## 结论

简单实用的方法是基于Ubuntu Docker image来安装dnsmasq。不建议放进一个scratch-based Docker image。

## 原因

dnsmasq确实可以被build成一个statically linked binary file，不依赖其他任何shared library，并且放进一个scratch-based Docker image。但是dnsmasq的运行需要很多其他依赖——比如scratch Docker image里没有/etc/passwd文件，所有进程以nobody的身份运行；而dnsmasq不接受以nobody身份运行自己，会抱怨并且退出。

## 实验

### 尝试一：从Ubuntu image里提取dnsmasq binary

为了得到dnsmasq的binary文件，并且考察dnsmasq依赖哪些其他文件，我`docker run --rm -it ubuntu:14.04 /bin/bash`，并且在container里运行`apt-get update && apt-get install -y dnsmasq`安装了dnsmasq。随后`dpkg-query -L dnsmasq`可以列出都安装了哪些文件。根据这个列表，我发现dnsmasq只是一个binary file，依赖一个配置文件/etc/dnsmasq.conf。但是这个binary依赖一些基础的shared libraries，比如libgcc.so。这些文件是scratch Docker image里没有的。

### 尝试二：从

**Comment by Yancey1989** [comment]
已经通过pkg add的方式来安装,后续如果有更新再reopen这个issue吧。
