### ISSUE TITLE
DNS记录的IP与hostname不匹配

### ISSUE THREAD

**Issue by Yancey1989** [k8sp/sextant#127]
如题，解释一下看到的现象：

1. 服务器启动直到使用coreos-install 加载CCTS提供的cloud-config文件，重启CoreOS之后，CoreOS的hostname和本机IP对应不上，如图所示：
![img_0840](https://cloud.githubusercontent.com/assets/1426912/17781032/319ef0f6-65a0-11e6-98a1-a97c264a192c.JPG)

2. 启动过程DHCP会分配给服务器三个IP地址，分别是

* 从tftp获取coreos镜像之前，DHCP会分配一个IP地址，称为IP0
* 加载从CCTS获取的cloud-config文件，配置hostname，安装kubernetes会得一个IP1
* 系统重启，会得到一个新的IP2

DNS中记录的hostname对应的IP为IP1，而不是新的IP2，不知道是否有人遇到同样的问题？

**Comment by pineking** [comment]
@Yancey1989 感觉不应该啊，
能看到 log 文件或者 /var/lib/dnsmasq/dnsmasq.leases 吗？
另外一个问题，为什么重启一下就获得一个新的IP2，按理说， lease time 没这么短吧，lease time设得多少？

**Comment by wangkuiyi** [comment]
@Yancey1989 @pineking 好吓人啊！谁能跟进一下这个问题吗？

**Comment by pineking** [comment]
@Yancey1989 @wangkuiyi 会不会是本机 DNS 缓存导致这个问题？需要确认下

**Comment by Yancey1989** [comment]
@pineking 好的，我去确认DNS缓存的问题，lease time设置的是12h。
@wangkuiyi 我在跟进这个，在集群上测试ccts时发现的这个问题。

**Comment by pineking** [comment]
@Yancey1989 lease time 可以设置长一点， 先确认bootstrapper上的dnsmasq 在dnsmasq.leases 的内容是否是正常的，再去确认是不是DNS缓存的问题

**Comment by Yancey1989** [comment]
@pineking 看起来不是lease time的问题，在cloud-config中配置网络模块，dns解析正常：
```
[Match]
Name=eht0

[Network]
DHCP=ipv4
```
问题的原因还需要继续看一下

**Comment by typhoonzero** [comment]
PXE boot的时候的确会存在和安装之后不同的IP。如果一台机器PXE连续安装两次，DNS纪录就会出问题么？

**Comment by Yancey1989** [comment]
DHCP默认是DHCPv6的，改成ipv4没问题，怀疑ipv6需要在dnsmasq配置才能使dhcp结合dns，先不纠结这个问题了。
DHCP的文档在这里：
https://www.freedesktop.org/software/systemd/man/systemd.network.html#%5BNetwork%5D%20Section%20Options
