### ISSUE TITLE
[讨论] auto-install repo的目录结构

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#137]
当我们说auto-install完工的时候，是不是应该包括以下目录：

```
auto-install
├── boostrapper
├── bsroot
├── cloud-config-server
└── docker
```

其中:

1. bsroot 里是一些用来下载文件的`download-*.bash`，一些用来build程序的`build-*.sh`，和一些模板（比如`example-cluster-desc.yml`）。

1. bootstrapper 根据 cluster-desc.yml 生成 bsroot 里重要配置文件，包括 dnsmasq.conf 和 registry.yml。

1. cloud-config-server 是要被 bsroot/build-ccs.bash build 并且放进 bsroot 里，以便 bootstrapper Docker container执行的。

1. docker里包括Dockerfile来生成bootstrapper Docker image。

**Comment by typhoonzero** [comment]
下面是我想象中的结构，有些区别：
```
auto-install
├── cloud-config-server/
          ├── cloud-config.template
          ├── cluster-desc.yml
          ├── template/
          └── cluster-desc/
├── scripts/
├── Dockerfile
├── start.sh
├── prepare.sh
├── build.sh
└── README.md
```
* cloud-config-server包含模版解析模块template和集群配置解析模块cluster-desc以及两个实例配置文件。
* scripts/包含download-*.bash和build-*.sh
* Dockerfile直接使用用于启动容器中dnsmasq, cc server, registry的脚本start.sh
* prepare.sh调用scripts/中的内容，完成bsroot的初始化工作
* build.sh调用scripts/中的内容，完成编译工作

**Comment by wangkuiyi** [comment]
@typhoonzero 我在 https://github.com/k8sp/auto-install/pull/133#discussion_r75592906 解释了为什么Dockerfile不能放在根目录里，而是得放在一个叶子目录里。所以docker目录我估计是得有的。

start.sh, prepare.sh, build.sh 的宾语不明显。如果放在bsroot目录里，我们可以猜想prepare.sh的意思是“prepare bsroot”，但是放在根目录下，prepare的宾语和build和宾语都不是一个了——prepare的宾语是"bsroot"，build的宾语是"bootstrapper Docker image"。

**Comment by Yancey1989** [comment]
LGTM, 是否少一个cloud-config-server和boostrapper里都需要的解析yml文件的模```config```？还是说整合到cloud-config-server里面了？
```
auto-install
├── boostrapper
├── bsroot
├── config
├── cloud-config-server
└── docker
```

**Comment by wangkuiyi** [comment]
确实需要cluster-desc.yml。因为是cloud-config-server和bootstrapper都需要的，所以我理解适合放在bsroot里。

**Comment by wangkuiyi** [comment]
我在 #135 里按照 @typhoonzero 的建议，把目前各种bash挪到bsroot/.scripts里了，然后用bsroot/init.bash 来调用他们。
