### ISSUE TITLE
[讨论] build bsroot目录里的内容

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#138]
在 #135 里，我写了一些bash程序来负责下载文件和build程序。此外，还有一些文件（比如pxelinux的配置文件是我写死的）。这样bootstrapper只需要根据 cluster-desc.yml 生成几个配置文件。这样看上去bsroot目录里有很多文件，#135 也显得很大。

之前我们的有一个很极端的思路——让bootstrapper程序来生成配置文件，来下载文件，来build和安装程序。把所有这些工作都放到bootstrapper里会让bootstrapper开发起来很慢。我看在 #113 里，有一个 bsroot.sh 作用和我们之前指望bootstrapper程序做的事情类似。但是这个bsroot.sh要想写好写完备，也不容易——还是用Go的模板替换生成配置文件比较方便。

我估计最后的路子会是一些bash脚本和bootstrapper并存。具体并存成什么样，还可以一边推进，一边考虑考虑。

**Comment by typhoonzero** [comment]
嗯。8月底的版本我觉得只要是一个work的版本就可以。使用模版生成配置文件的go程序，可以逐步迭代merge到master。

**Comment by wangkuiyi** [comment]
赞同！
