### ISSUE TITLE
CoreOS version retrieval

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#139]
I confirmed by reading the source of `/usr/bin/coreos-install` that the script retrieves the most recent version by accessing `${BASE_URL}/${VERSION_ID}/version.txt`, where `${BASE_URL}` is specified via the `-b` parameter.

```
# if the version is "current", resolve the actual version number
if [[ "${VERSION_ID}" == "current" ]]; then
    VERSION_ID=$(wget --quiet -O - "${BASE_URL}/${VERSION_ID}/version.txt" | \
        gawk --field-separator '=' '/COREOS_VERSION=/ { print $2 }')
    echo "Current version of CoreOS ${CHANNEL_ID} is ${VERSION_ID}"
fi
```

**Comment by wangkuiyi** [comment]
So, if we want to upgrade the CoreOS version of the cluster, we just update the `bsroot/www/current/version.txt` file on the bootstrapper server.

**Comment by jiamliang** [comment]
今天早上我在想，以后怎么自动获取最新的版本放在服务器上，于是没有多想，就写了一行脚本来获取最新的版本号：
curl https://stable.release.core-os.net/amd64-usr/ 2>&1 | grep dir | grep -v current | awk -F"<|>" '{v=$3} END {print v}'
上面的方法挺优雅的。

**Comment by typhoonzero** [comment]
嗯，这个我也发现了，在https://github.com/k8sp/auto-install/pull/113 中的install.sh中使用命令：
```
sudo coreos-install -d /dev/sda -c ${mac_addr}.yml -b http://<HTTP_ADDR>/static -V current
```
安装，用参数-V current指定从current目录下根据version.txt安装最新的版本。这样initcoreos这个branch的代码也可以做对应的更新，提供最新CoreOS的镜像
