### ISSUE TITLE
Cross-compile all binaries in bootstrapper Docker image before docker build

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#140]
只要在 `bsroot/.script/`里增加一个`build-dnsmasq`，我们就可以构建一个非常小的Docker image，在里面运行由 `bsroot/init.bash`在`docker build`之前预先build好的 `bsroot/dnsmasq`, `bsroot/cloud-config-server`和 `bsroot/registry`。

这样不仅让 Docker image的base image可以由`golang:alpine`，变成只有16MB的`alpine`。而且即使bootstrapper server上没有Docker，我们也可以直接运行 `bsroot/start.bash`来在操作系统上直接启动 dnsmasq, cloud-config-server和registry。

**Comment by typhoonzero** [comment]
现在可以尝试改成用alpine而不是glang:alpine了，binary都改成了静态

**Comment by JunfeiYang** [comment]
#396 里面已经修复了这个问题
