### ISSUE TITLE
bootstrapper需要最后自动安装skydns, ingress, heapster/influxdb/grafana组件

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/sextant#155]
如题，需要在k8s集群初始化之后： 

- [ ] 自动安装skydns, ingress, heapster/influxdb/grafana
- [ ] 等待k8s集群有足够的node之后才提交这些组件
- [ ] 提交组件之后如何验证是可以正常工作的

**Comment by pineking** [comment]
heapster 可以参考：https://github.com/k8sp/heapster

**Comment by typhoonzero** [comment]
1. 在cloud-config-server中，根据cluster-desc和skydns的模版，生成本集群的skydns.yaml文件
1. 在start.sh中最后，循环检查master的8080端口是否可以联通，并等待
1. wget -O skydns.yaml http://localhost:8081/path/to/skydns.yaml
1. kubectl create -f skydns.yaml

**Comment by Yancey1989** [comment]
> 5. wget -O kubectl http://localhost:8081/static/kubectl && chmod +x kubectl
这里还需要kubectl的配置工作
kubectl set-cluster ....

另外对ingress来说还需要增加

1. wget -O ingress.yaml http://localhost:8081/path/to/ingress.yaml
1. 检查在cluster-desc中配置为ingress的机器是否ready，如果ready则通过kubectl 对该node打label

**Comment by Yancey1989** [comment]
@typhoonzero 我来提个PR吧，把Ingress的事情和这个一块来实现。

**Comment by typhoonzero** [comment]
@Yancey1989 赞
