### ISSUE TITLE
boostrapper自动安装ingress

### ISSUE THREAD

**Issue by Yancey1989** [k8sp/sextant#156]
follow #155 
梳理一下安装ingress的步骤，各位看下是否有遗漏的地方

1. 因为ingress需要部署在有外网IP的服务器上，所以cluster-desc中需要有确定哪些机器可以作为ingress
2. 由于前端机有多块网卡，flanneld需要绑定到内网的网卡上，所以cloud-config server中生成的cc文件需要做相应调整
3. ingress是以pod方式提交到集群，并且只能在前端机上运行，所以需要对node打label，在rc中使用nodeselector选择对应的node。

**Comment by typhoonzero** [comment]
集群初始化之后，应该还有许多未处理的步骤：

* kube-system pod的提交：skydns, ingress, heapster
* 给节点打label

**Comment by typhoonzero** [comment]
Duplicate https://github.com/k8sp/sextant/issues/155

**Comment by Yancey1989** [comment]
@typhoonzero #155 作为task的记录吧，这个issue负责把ingress的事情讨论清楚。

**Comment by Yancey1989** [comment]
看起来这和skydns是一个通用的流程，那么放在#155 中一块讨论吧：）
