### ISSUE TITLE
service IP 配置变量放在一起，方便查找

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#159]
为了配置 skydns，需要找到 k8s 里的 --cluster-dns 的配置，
在这里，
https://github.com/k8sp/sextant/blob/master/cloud-config-server/template/cloud-config.template#L359

我看到是直接在里面写死的，包括  service IP range
https://github.com/k8sp/sextant/blob/master/cloud-config-server/template/cloud-config.template#L74

而我们以后把自动配置 skydns 加进来，需要 cluster-dns的值，所以

* 建议不要写死，用个变量保存下来，便于 skydns 配置
* 建议放到把这些 IP 相关的变量集中放在一起，便于查找

**Comment by pineking** [comment]
@Yancey1989 skydns @sunxs1101兴帅已经配好了，有问题你们俩可以沟通下

**Comment by Yancey1989** [comment]
@pineking 确实有这个问题，这个cluster-dns的地址写在cluster-desc中是不是就可以了？

**Comment by pineking** [comment]
@Yancey1989 嗯，我觉得可以，主要是能找到一个集中设置的地方，方便查找
另外一点，这个cluster-dns 是k8s 集群内部 service 的 dns，在变量命名上要和物理机的dns区别开来。

**Comment by Yancey1989** [comment]
有道理，稍后我提个PR，还请帮忙Review下。
