### ISSUE TITLE
flanneld.service 启动出错

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#164]
etcd 服务正常
说明 CoreOS 为 1068.10.0 的机器正常， 1122.2.0 版本启动出错

CoreOS 版本信息：
00-25-90-c0-f7-80 core # cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

**systemctl start flanneld 出错， log 如下：**

▒~W~O flanneld.service - Network fabric for containers
   Loaded: loaded (/usr/lib64/systemd/system/flanneld.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/flanneld.service.d
           ▒~T~T▒~T~@50-network-config.conf
   Active: activating (auto-restart) (Result: exit-code) since Mon 2016-09-12 10:15:24 CST; 316ms ago
     Docs: https://github.com/coreos/flannel
  Process: 14801 ExecStopPost=/usr/bin/rkt gc --mark-only (code=exited, status=0/SUCCESS)
  **Process: 14779 ExecStart=/usr/bin/rkt run --net=host --stage1-path=/usr/lib/rkt/stage1-images/stage1-fly.aci --insecure-options=image --set-env=NOTIFY_SOCKET=/run/systemd/notify --inherit-env=true --volume runsystemd,kind=host,source=/run/systemd,readOnly=false --volume runflannel,kind=host,source=/run/flannel,readOnly=false --volume ssl,kind=host,source=${ETCD_SSL_DIR},readOnly=true --volume certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume resolv,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=runsystemd,target=/run/systemd --mount volume=runflannel,target=/run/flannel --mount volume=ssl,target=${ETCD_SSL_DIR} --mount volume=certs,target=/etc/ssl/certs --mount volume=resolv,target=/etc/resolv.conf ${FLANNEL_IMG}:${FLANNEL_VER} --exec /opt/bin/flanneld -- --ip-masq=true (code=exited, status=1/FAILURE)**
  Process: 14768 ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config { "Network": "10.1.0.0/16" } (code=exited, status=0/SUCCESS)
  Process: 14765 ExecStartPre=/usr/bin/mkdir -p ${ETCD_SSL_DIR} (code=exited, status=0/SUCCESS)
  Process: 14762 ExecStartPre=/usr/bin/mkdir -p /run/flannel (code=exited, status=0/SUCCESS)
  Process: 14754 ExecStartPre=/sbin/modprobe ip_tables (code=exited, status=0/SUCCESS)
 Main PID: 14779 (code=exited, status=1/FAILURE)

Sep 12 10:15:24 00-25-90-c0-f7-80 systemd[1]: Failed to start Network fabric for containers.
Sep 12 10:15:24 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Unit entered failed state.
Sep 12 10:15:24 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Failed with result 'exit-code'.

**flanneld.service log 信息**

00-25-90-c0-f7-80 core # journalctl -u flanneld.service -f
-- Logs begin at Wed 2016-08-31 16:29:57 CST. --
Sep 12 10:31:02 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Service hold-off time over, scheduling restart.
Sep 12 10:31:02 00-25-90-c0-f7-80 systemd[1]: Stopped Network fabric for containers.
Sep 12 10:31:02 00-25-90-c0-f7-80 systemd[1]: Starting Network fabric for containers...
Sep 12 10:31:02 00-25-90-c0-f7-80 etcdctl[23978]: { "Network": "10.1.0.0/16" }
Sep 12 10:31:02 00-25-90-c0-f7-80 rkt[23990]: image: using image from file /usr/lib/rkt/stage1-images/stage1-fly.aci
**Sep 12 10:31:03 00-25-90-c0-f7-80 rkt[23990]: run: an unsupported URL scheme "bootstrapper" - the only URL schemes supported by rkt are docker, http, https and file**
Sep 12 10:31:03 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 10:31:03 00-25-90-c0-f7-80 systemd[1]: Failed to start Network fabric for containers.
Sep 12 10:31:03 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Unit entered failed state.
Sep 12 10:31:03 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Failed with result 'exit-code'.
Sep 12 10:31:08 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Service hold-off time over, scheduling restart.
Sep 12 10:31:08 00-25-90-c0-f7-80 systemd[1]: Stopped Network fabric for containers.
Sep 12 10:31:08 00-25-90-c0-f7-80 systemd[1]: Starting Network fabric for containers...
Sep 12 10:31:08 00-25-90-c0-f7-80 etcdctl[24036]: { "Network": "10.1.0.0/16" }
Sep 12 10:31:08 00-25-90-c0-f7-80 rkt[24048]: image: using image from file /usr/lib/rkt/stage1-images/stage1-fly.aci
**Sep 12 10:31:09 00-25-90-c0-f7-80 rkt[24048]: run: an unsupported URL scheme "bootstrapper" - the only URL schemes supported by rkt are docker, http, https and file**
Sep 12 10:31:09 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 10:31:09 00-25-90-c0-f7-80 systemd[1]: Failed to start Network fabric for containers.
Sep 12 10:31:09 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Unit entered failed state.
Sep 12 10:31:09 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Failed with result 'exit-code'.
Sep 12 10:31:14 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Service hold-off time over, scheduling restart.
Sep 12 10:31:14 00-25-90-c0-f7-80 systemd[1]: Stopped Network fabric for containers.
Sep 12 10:31:14 00-25-90-c0-f7-80 systemd[1]: Starting Network fabric for containers...
Sep 12 10:31:14 00-25-90-c0-f7-80 etcdctl[24094]: { "Network": "10.1.0.0/16" }
Sep 12 10:31:14 00-25-90-c0-f7-80 rkt[24105]: image: using image from file /usr/lib/rkt/stage1-images/stage1-fly.aci
**Sep 12 10:31:14 00-25-90-c0-f7-80 rkt[24105]: run: an unsupported URL scheme "bootstrapper" - the only URL schemes supported by rkt are docker, http, https and file**
Sep 12 10:31:14 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 10:31:14 00-25-90-c0-f7-80 systemd[1]: Failed to start Network fabric for containers.
Sep 12 10:31:14 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Unit entered failed state.
Sep 12 10:31:14 00-25-90-c0-f7-80 systemd[1]: flanneld.service: Failed with result 'exit-code'.

**Comment by typhoonzero** [comment]
rkt很坑啊，需要在cloud-config.template中将flanneld的启动方式改成使用docker启动。我提个pr吧
