### ISSUE TITLE
默认bootstrapper server的IP的配置

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#173]
在[bsroot.sh](https://github.com/k8sp/sextant/blob/master/bsroot.sh#L5)里，我们解析cloud-config-server[模板文件](https://github.com/k8sp/sextant/blob/master/cloud-config-server/template/unisound-ailab/build_config.yml#L1)里的默认bootstrapper server IP地址，作为bootstrapper IP。这个貌似没有什么特别的道理？毕竟那个目录的名字叫*unisound-ailab*，要是其他公司的机群，bootstrapper server的IP可能和云知声的不一样？

```
# FIXME: DEFAULT_IPV4 may not accessible by clients?
#DEFAULT_IPV4=`ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'`
DEFAULT_IPV4=`grep "bootstrapper:" cloud-config-server/template/unisound-ailab/build_config.yml | awk '{print $2}' | sed 's/ //g'`
echo "using bootstrapper IP: $DEFAULT_IPV4..."
```

**Comment by typhoonzero** [comment]
目录名需要修改成通用的一个名字。build_config.yml文件名也需要修改成为cluster-desc.yml。

这么做的原因是，bootstrapper server可能有多个网卡或多个IP地址，而用作初始化集群的那个网卡或IP是无法通过程序来自动确定的，需要通过配置指定，这个配置就是cluster-desc。所以初始化bsroot之前，一定要先配置好cluster-desc.yml才能保证生成的bsroot是正确的

**Comment by wangkuiyi** [comment]
明白了！所以这里应该parse的不是 `cloud-config-server/template/unisound-ailab/build_config.yml`，而是作为bsroot.sh参数传进来的一个cluster-desc.yml文件？

**Comment by typhoonzero** [comment]
是的！

**Comment by typhoonzero** [comment]
我稍后按照这个思路提一个pr～

**Comment by wangkuiyi** [comment]
棒！我正在修改bsroot.sh，看看可否产生./bsroot，而不是 /bsroot。我顺便搞搞就好

**Comment by typhoonzero** [comment]
收到
