### ISSUE TITLE
function gen_dnsmasq_conf in bsroot.sh needs to parse cluster-desc.yml

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#174]
目前，[gen_dnsmasq_conf 函数](https://github.com/k8sp/sextant/blob/master/bsroot.sh#L61) 用了好多参数，都是写死的。实际上这些参数应当从 cluster-desc.yml 里获得？

**Comment by typhoonzero** [comment]
已经使用addons通过template的方式里，根据cluster-desc来生成dnsmasq的配置了。关闭本issue。
