### ISSUE TITLE
bsroot.sh 没有替换模板 cloud-config-server/install.sh 里的变量

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#175]
[看上去](https://github.com/k8sp/sextant/blob/master/bsroot.sh#L128)，bsroot.sh只是拷贝了 cloud-config-server/install.sh 这个文件，却没有替换其中的变量 `<HTTP_ADDR>`？

另外，cloud-config-server/install.sh 这个文件的内容可以写进 bsroot.sh，也就不需要这个文件了？

**Comment by typhoonzero** [comment]
1. 已开始考虑是：bsroot.sh执行的位置不一定是在bootstrapper server，也有可能是自己的笔记本，所以此时无法自动获得IP。就做成在start.sh替换变量```<HTTP_ADDR>```了。现在都以cluster-desc为基准的话，就可以简化这个步骤

**Comment by wangkuiyi** [comment]
明白了！
