### ISSUE TITLE
mac地址作为主机名出现的问题

### ISSUE THREAD

**Issue by JunfeiYang** [k8sp/sextant#176]
在使用mac地址作为主机名时，获得mac地址不是我们想要的结果；
 操作环境：
   操作系统：coreos
   网络环境：
                     bond0 192.168.48.23
                     bond1 192.168.119.202
![ifconfig](https://cloud.githubusercontent.com/assets/16366286/18660305/4a904068-7f42-11e6-9366-6496dafbc511.png)
下面是 sextant/cloud-config-server/install.sh mac_addr获取的结果：
![mac_add](https://cloud.githubusercontent.com/assets/16366286/18660471/32fee624-7f43-11e6-86f1-92db48f30bb3.png)

我需要b0:83:fe:da:48:9c作为主机名，取得结果是两个mac地址倒数第一个。

**Comment by pineking** [comment]
bond0 是 default interface 吧
这个可以改下 cloud-config-server/install.sh mac_addr 的获取方式
