### ISSUE TITLE
bsroot.sh脚本执行后，docker run 参数需要在Readme更新

### ISSUE THREAD

**Issue by JunfeiYang** [k8sp/sextant#188]
## 描述
bsroot.sh 执行完成后，bsrtoot目录创建到sextant目录下，例如：sextant clone在/opt
最后生成目录：/opt/sextant/bsroot,docker run需修改参数:
docker run -d --net=host \
  --privileged \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /opt/sextant/bsroot:/bsroot \
  bootstrapper
在README文件中
![readme](https://cloud.githubusercontent.com/assets/16366286/18710208/808337bc-8036-11e6-81b4-556e29f09cc9.png)

**Comment by typhoonzero** [comment]
Should be closed, due to start_bootstrapper_container.sh always needs an argument to specify the bsroot path.
