### ISSUE TITLE
work节点启动etcd proxy 报错

### ISSUE THREAD

**Issue by JunfeiYang** [k8sp/sextant#197]
## 描述

k8s环境安装work节点时，本机主机名（ec-f4-bb-da-a3-55）mac地址为（ec:f4:bb:da:a3:55）生成ec:f4:bb:da:a3:55.yaml文件。/run/systemd/system/etcd2.service.d/20-cloudinit.conf
![etcd2](https://cloud.githubusercontent.com/assets/16366286/18743818/6fa312c0-80ed-11e6-95b8-4a8b3c066b2e.png)
### etcd2 member

b0-83-fe-da-48-9c=http://b0-83-fe-da-48-9c:2380,
ec-f4-bb-d4-09-4d=http://ec-f4-bb-d4-09-4d:2380,
ec-f4-bb-d9-8f-65=http://ec-f4-bb-d9-8f-65:2380"
### 启动etcd2 proxy ,出现以下问题：

Sep 12 16:33:01 coreos1 systemd[1]: Starting etcd2...
-- Subject: Unit etcd2.service has begun start-up
-- Defined-By: systemd
## -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit etcd2.service has begun starting up.
Sep 12 16:33:01 coreos1 etcd2[1574]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://:2379,http://:4001
Sep 12 16:33:01 coreos1 etcd2[1574]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Sep 12 16:33:01 coreos1 etcd2[1574]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/<discovery_token>
Sep 12 16:33:01 coreos1 etcd2[1574]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://:2380
Sep 12 16:33:01 coreos1 etcd2[1574]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Sep 12 16:33:01 coreos1 etcd2[1574]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://:2380
Sep 12 16:33:01 coreos1 etcd2[1574]: recognized and used environment variable ETCD_NAME=04cfffdc2c3b4be9a18c473df6700f6c
Sep 12 16:33:01 coreos1 etcd2[1574]: etcd Version: 2.3.1
Sep 12 16:33:01 coreos1 etcd2[1574]: Git SHA: 2b67f52
Sep 12 16:33:01 coreos1 etcd2[1574]: Go Version: go1.5.3
Sep 12 16:33:01 coreos1 etcd2[1574]: Go OS/Arch: linux/amd64
Sep 12 16:33:01 coreos1 etcd2[1574]: setting maximum number of CPUs to 24, total number of available CPUs is 24
Sep 12 16:33:01 coreos1 etcd2[1574]: listening for peers on http://:2380
Sep 12 16:33:01 coreos1 etcd2[1574]: listening for client requests on http://0.0.0.0:2379
Sep 12 16:33:01 coreos1 etcd2[1574]: listening for client requests on http://0.0.0.0:4001
Sep 12 16:33:01 coreos1 etcd2[1574]: resolving :2380 to :2380
Sep 12 16:33:01 coreos1 etcd2[1574]: resolving :2380 to :2380
Sep 12 16:33:01 coreos1 etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 16:33:01 coreos1 etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 2s
Sep 12 16:33:03 coreos1 etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 16:33:03 coreos1 etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 4s
Sep 12 16:33:07 coreos1 etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 16:33:07 coreos1 etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 8s
Sep 12 16:33:15 coreos1 etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 16:33:15 coreos1 etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 16s
Sep 12 16:33:31 coreos1 etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 16:33:31 coreos1 etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 32s
Sep 12 16:34:03 coreos1 etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 16:34:03 coreos1 etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 1m4s
Sep 12 16:35:07 coreos1 etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 16:35:07 coreos1 etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 2m8s
Sep 12 16:37:15 coreos1 etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 16:37:15 coreos1 etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 4m16s
Sep 12 16:41:31 coreos1 etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 16:41:31 coreos1 etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 8m32s
Sep 12 16:50:03 coreos1 etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 16:50:03 coreos1 etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 17m4s
Sep 12 17:07:07 coreos1 etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 17:07:07 coreos1 etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 34m8s
Sep 12 17:41:15 coreos1 etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 17:41:15 coreos1 etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 1h8m16s
Sep 12 18:49:31 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 18:49:31 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 2h16m32s
Sep 12 21:06:03 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 12 21:06:03 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 4h33m4s
Sep 13 01:39:07 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 13 01:39:07 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 9h6m8s
Sep 13 10:45:15 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 13 10:45:15 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 18h12m16s
Sep 14 04:57:31 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 14 04:57:31 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 36h24m32s
Sep 15 17:22:03 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 15 17:22:03 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 72h49m4s
Sep 18 18:11:07 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Sep 18 18:11:07 bjlg-48p26-k8s-04.bfdabc.com etcd2[1574]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 145h38m8s
Sep 19 11:48:38 bjlg-48p26-k8s-04.bfdabc.com systemd[1]: etcd2.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 19 11:48:38 bjlg-48p26-k8s-04.bfdabc.com systemd[1]: Stopped etcd2.
-- Subject: Unit etcd2.service has finished shutting down

**Comment by pineking** [comment]
看起来像域名解析的问题， 在 worker 节点上 dig discovery.etcd.io 正常吗?

**Comment by JunfeiYang** [comment]
dig 下面的信息；
dig  discovery.etcd.io 
; <<>> DiG 9.10.2-P4 <<>> discovery.etcd.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53955
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 13, ADDITIONAL: 12

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;discovery.etcd.io.		IN	A

;; ANSWER SECTION:
discovery.etcd.io.	1070	IN	CNAME	discovery-etcd-io-v3-1716035837.us-west-1.elb.amazonaws.com.
discovery-etcd-io-v3-1716035837.us-west-1.elb.amazonaws.com. 42	IN A 54.193.122.242
discovery-etcd-io-v3-1716035837.us-west-1.elb.amazonaws.com. 42	IN A 54.183.22.106
discovery-etcd-io-v3-1716035837.us-west-1.elb.amazonaws.com. 42	IN A 54.183.252.41

;; AUTHORITY SECTION:
com.			45936	IN	NS	i.gtld-servers.net.
com.			45936	IN	NS	j.gtld-servers.net.
com.			45936	IN	NS	k.gtld-servers.net.
com.			45936	IN	NS	l.gtld-servers.net.
com.			45936	IN	NS	m.gtld-servers.net.
com.			45936	IN	NS	a.gtld-servers.net.
com.			45936	IN	NS	b.gtld-servers.net.
com.			45936	IN	NS	c.gtld-servers.net.
com.			45936	IN	NS	d.gtld-servers.net.
com.			45936	IN	NS	e.gtld-servers.net.
com.			45936	IN	NS	f.gtld-servers.net.
com.			45936	IN	NS	g.gtld-servers.net.
com.			45936	IN	NS	h.gtld-servers.net.

;; ADDITIONAL SECTION:
c.gtld-servers.net.	16040	IN	A	192.26.92.30
d.gtld-servers.net.	78968	IN	A	192.31.80.30
e.gtld-servers.net.	34382	IN	A	192.12.94.30
f.gtld-servers.net.	34382	IN	A	192.35.51.30
g.gtld-servers.net.	34382	IN	A	192.42.93.30
h.gtld-servers.net.	34382	IN	A	192.54.112.30
i.gtld-servers.net.	35069	IN	A	192.43.172.30
j.gtld-servers.net.	15431	IN	A	192.48.79.30
k.gtld-servers.net.	34563	IN	A	192.52.178.30
l.gtld-servers.net.	71734	IN	A	192.41.162.30
m.gtld-servers.net.	71734	IN	A	192.55.83.30

;; Query time: 0 msec
;; SERVER: 192.168.49.167#53(192.168.49.167)
;; WHEN: Thu Sep 22 19:21:07 CST 2016
;; MSG SIZE  rcvd: 567

**Comment by pineking** [comment]
应该是哪里有bug，变量为空，导致IP没了

ETCD_LISTEN_PEER_URLS=http://:2380

**Comment by JunfeiYang** [comment]
sextant 代码更新，解决了问题。
