### ISSUE TITLE
addons 缺少说明

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#200]
[addons](https://github.com/k8sp/sextant/tree/master/addons) 这个目录里需要一个README.md文件，说明这个模块是干什么的，为什么需要，怎么使用。

类似的，每个目录都应该有README.md。

此外，addon这个名字意思太“泛”。不够具体。需要改一个名字。

**Comment by Yancey1989** [comment]
addon这个名字是根据社区https://github.com/kubernetes/kubernetes/tree/master/cluster/addons 的名字而来的，原本是为了方便和社区统一命名而起的。或者改为addone-gen更好一些？
