### ISSUE TITLE
因为Dockerfile里go get github.com/...sextant，所以只能build master branch的Docker image

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#203]
需要琢磨一下，可否不调用go get，而是用本地的源码来go build。

**Comment by wangkuiyi** [comment]
试验了一下，确实不需要go get，只需要在Dockerfile里用ADD：

```
FROM golang:alpine

ENV GOPATH /var/go
RUN mkdir -p /var/go/src/github.com/wangkuiyi/learn-docker
ADD a_program /var/go/src/github.com/wangkuiyi/learn-docker/a_program
RUN go install github.com/wangkuiyi/learn-docker/a_program

ENTRYPOINT ["/var/go/bin/a_program"]
```

一个完整的验证了可用的例子在 https://github.com/wangkuiyi/learn-docker-golang/blob/master/Dockerfile

验证过程如下：

```
go get -u github.com/wangkuiyi/learn-docker-golang
cd $GOPATH/src/github.com/wangkuiyi/learn-docker-golang
docker build -t ap .
docker run ap
```

最后一行执行Docker image `ap`。输出结果符合预期：

```
$ docker run ap
How Docker works with Go?
```

**Comment by wangkuiyi** [comment]
上述例子太过简单了。实际情况是，cloud-config-server 还有其他dependencies需要下载。而 `go get ./...`虽然可以分析和下载所有dependencies，但是它要求所在branch必须已经是git push到remote repo上的 —— go get 对源码的source version control system以及相应配置有要求！而在本地执行 `docker build -t bootstrapper .`的时候，本地sextant branch可能还没有git push到远地。

**Comment by wangkuiyi** [comment]
看上去一个相对靠谱的方法是：

1. 在`docker build -t bootstrapper .`之前，在本地build好`sextant/cloud-config-server`和`sextant/addons`，
1. 在 Dockerfile 里只是把 `$GOPAHT/bin/{cloud-config-server,addons}`加入到Docker images里。

**Comment by Yancey1989** [comment]
@wangkuiyi 的方法靠谱
> 1. 在`docker build -t bootstrapper .`之前，在本地build好`sextant/cloud-config-server`和`sextant/addons`，

这里可能编译的机器没有golang环境，建议通过一个拥有编译环境的docker image，在这个image里进行编译，再将二进制文件通过```docker cp```拷到本地。

**Comment by wangkuiyi** [comment]
@Yancey1989 我想到这个了。其实安装go比安装docker容易多了 ——

不管在哪种Linux distribution还是mac下，安装go都只需要下载对应的tar.gz，并且untar；而每种Linux distribution安装Docker的方式都不一样，比如这里列出了各种Linux distribution上安装docker的方法：https://docs.docker.com/engine/installation/ ，尤其是mac上安装docker更奇特： https://docs.docker.com/engine/installation/mac/

**Comment by Yancey1989** [comment]
@wangkuiyi 明白了，只是依赖go的话确实是安装go环境比较简单。
