### ISSUE TITLE
bsroot.sh下载Kubernetes以利用kubelet。但是Kubernetes太太，导致Sextant使用不便

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#206]
之前WeChat讨论中, @pineking 支出貌似不需要也不应该在cloud-config文件里建立一个systemd unit来执行kubelet。

此时请 @typhoonzero 和 @pineking 再讨论一下，希望有简单的做法解决之前的问题。

**Comment by typhoonzero** [comment]
改成以hyperkube的docker镜像来启动kubelet应该可行，我测一下

**Comment by wangkuiyi** [comment]
这里说的“启动kubelet”是指在Kubernetes机群的机器上启动kubelet吗？我以为这些机器上的kubelet是运行在hyperkube container里的，所以不需要Sextant下载kubelet了？

**Comment by pineking** [comment]
@wangkuiyi @typhoonzero 之前 WeChat 讨论我意思是支持目前以 systemd unit 执行 kubelet binary 启动 kubelet

@typhoonzero 以 docker 方式启动有什么优势吗？还是只是为了解决不需要下载 kubelet binary 的问题？

**Comment by pineking** [comment]
我建议还是保持以 kubelet binary 和 systemd service的方式启动 kubelet

本 issues 提出的另外一个问题是下载 kubernetes 太大，导致使用不方便
我看了下
https://github.com/k8sp/sextant/blob/master/bsroot.sh#L171
https://github.com/k8sp/sextant/blob/master/bsroot.sh#L172

下载一个1个G的 kubernetes.tar.gz 而实际使用的仅仅是 kubelet 和 kubectl 这两个 binary 文件
不知道我理解对不对

如果理解是对的，那完全没必要下载整个 kubernetes.tar.gz 
下载 kubelet 和 kubectl 这两个 binary 文件，可以通过类似下面的方式单独下载，这样下载大小就会小很多

https://storage.googleapis.com/kubernetes-release/release/v1.3.6/bin/linux/amd64/kubelet
https://storage.googleapis.com/kubernetes-release/release/v1.3.6/bin/linux/amd64/kubectl

**Comment by wangkuiyi** [comment]
赞可以只下载kubelet和kubectl !

**Comment by pineking** [comment]
之前在 WeChat 讨论时， 我也提到 CoreOS 文档里是用 rkt 启动 kubelet
https://coreos.com/kubernetes/docs/1.3.6/deploy-master.html#create-the-kubelet-unit
https://coreos.com/kubernetes/docs/1.3.6/deploy-workers.html#create-the-kubelet-unit
https://github.com/coreos/coreos-overlay/blob/master/app-admin/kubelet-wrapper/files/kubelet-wrapper
https://github.com/kubernetes/kubernetes/issues/4869#issuecomment-237695622

但不清楚 CoreOS 为什么不以 docker 方式启动
这里有讨论以 docker 启动的问题：
https://github.com/kubernetes/kubernetes/issues/4869

我之前试过 kubelet binary 可以正常工作的，sextant 目前采用的也是调用 kubelet binary
不清楚调用 binary 方式启动 kubelet 有没有其他隐藏没被发现的问题

**Comment by pineking** [comment]
额外问个问题，kubectl 是不是在安装集群的时候不需要，在使用集群的时候才需要

**Comment by wangkuiyi** [comment]
会议讨论：

这个修改已经在 vm-cluster branch里实现了。但是vm-cluster还没有merge到master。  @lipeng-unisound 会把在vm-cluster里的fix挑出来，单独作为一个PR，merge到master。
