### ISSUE TITLE
bsroot.sh利用了个人账号里的Docker images

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#207]
[bsroot.sh](https://github.com/k8sp/sextant/blob/master/bsroot.sh#L234)里，很多基础服务用的不是official images，而是 @typhoonzero 和 @Yancey1989 的个人账号里的images。

```
  DOCKER_IMAGES=('typhoon1986/hyperkube-amd64:${hyperkube_version}' \
    'typhoon1986/pause:${pause_version}' \
    'typhoon1986/flannel:${flannel_version}' \
    'yancey1989/nginx-ingress-controller:0.8.3' \
    'yancey1989/kube2sky:1.14' \
    'typhoon1986/exechealthz:1.0' \
    'yancey1989/yancey1989/kube-addon-manager-amd64:v5.1' \
    'typhoon1986/skydns:latest');
```

为什么需要这样？如果一定需要，如何确保维护个人账号里的images和official images之间的对应关系？

**Comment by typhoonzero** [comment]
如 #209 所说，镜像的地址也需要可以配置而不是写死在脚本里。

**Comment by wangkuiyi** [comment]
需要配置吗？为什么不能直接用official的images呢？

**Comment by typhoonzero** [comment]
1. 墙的原因
2. image名称会发生变化，官方的pause镜像已经变成了pause-amd64

**Comment by wangkuiyi** [comment]
你和闫旭的images不在墙外吗？那个是不是我之前试验的时候，无法访问 docker.io的原因？

**Comment by typhoonzero** [comment]
docker.io墙内是能访问的，上次 @wangkuiyi 无法访问应该是暂时性的问题。

**Comment by typhoonzero** [comment]
ps: @JunfeiYang 说可以通过配置hosts也可以访问到gcr.io

**Comment by Yancey1989** [comment]
docker.io 目前在国内还可以访问，gci.io的目前还不行

**Comment by wangkuiyi** [comment]
会议讨论：

- 目前cluster-desc.yml里写各个重要镜像的version number，然后有一个路子把version number转变成各个image的fullname。

- 应该改成cluster-desc.yml里直接配置各个重要镜像的 fullnames，用它们的official URL。

以上修改请 @typhoonzero 负责。

**Comment by wangkuiyi** [comment]
Fix https://github.com/k8sp/sextant/issues/239 之后，来fix这个。这样vm-cluster出来之前，对bsroot.sh的验证可以通过unit test来做。
