### ISSUE TITLE
vm-cluster从vm-cluster repo加入到sextant repo

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#208]

**Comment by zhengbo0** [comment]
https://github.com/k8sp/sextant/pull/205，已提交，待俊飞review和测试

**Comment by wangkuiyi** [comment]
@JunfeiYang @lipeng-unisound @zhengbo0 验证一下 Vagrantfile 里synced folder可用，具体在 https://github.com/k8sp/sextant/issues/228。

另外，https://github.com/k8sp/sextant/issues/244 的问题也争取尽快修复。

随后，我们把vm-cluster的Vagrantfile这一套merge到master。
