### ISSUE TITLE
将bootstrapper用到的docker image的地址和tag都在cluster-desc中配置

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/sextant#209]
目前只修改成了可以配置image tag，然而现在都用的个人的镜像repo，所以需要让这些镜像地址可配置，以便后续修改地址。

**Comment by wangkuiyi** [comment]
这个issue实际上适合作为 https://github.com/k8sp/sextant/issues/207 里的一个comment。在那个issue里讨论清楚，大家达成一个共识，再发一个PR fix 那个issue，这样比较简洁高效吧。
