### ISSUE TITLE
cluster yaml 关于集群网络的配置与 dnsmasq.conf 配置不统一

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#213]
cluster yaml 关于集群网络的配置
https://github.com/k8sp/sextant/blob/master/cloud-config-server/template/unisound-ailab/build_config.yml
与 dnsmasq.conf 配置
https://github.com/k8sp/sextant/blob/master/bsroot.sh#L96
不统一

期望能在 cluster yaml 里配置完成后，自动生成相应的 dnsmasq.conf 配置，不需要手工再修改维护 dnsmasq.conf 配置

**Comment by wangkuiyi** [comment]
赞！

**Comment by wangkuiyi** [comment]
@typhoonzero 建议修改 addon 来做这一个工作，而不是在bsroot.sh里做，因为shell script不容易parse YAML配置文件。
