### ISSUE TITLE
建议cluster description 文件命名为 cluster-desc.sample.yaml

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#217]
目前 cluster description 文件全路径为 `cloud-config-server/template/unisound-ailab/build_config.yml`
建议改为  `cloud-config-server/template/cluster-desc.sample.yaml`

文件路径中删除了 `unisound-ailab`
同时文件后缀从 `yml` 改为 `yaml`
建议其他 YAML 文件的后缀名也从 `yml` 改为 `yaml`

**Comment by wangkuiyi** [comment]
赞同这个建议！之前和郑波的一次技术讨论里也聊到了。
