### ISSUE TITLE
vm-cluster分支 entrypoint.sh执行报错/entrypoint.sh: line 36: syntax error: unexpected "("

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/sextant#224]
编译完docker image之后docker run报错：
```
Sep 24 09:05:13 dnsmasq[21]: started, version 2.76 cachesize 150
Sep 24 09:05:13 dnsmasq[21]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
Sep 24 09:05:13 dnsmasq-dhcp[21]: DHCP, IP range 192.168.8.102 -- 192.168.8.200, lease time 12h
Sep 24 09:05:13 dnsmasq-dhcp[21]: DHCP, sockets bound exclusively to interface eth0
Sep 24 09:05:13 dnsmasq-tftp[21]: TFTP root is /bsroot/tftpboot
Sep 24 09:05:13 dnsmasq[21]: using local addresses only for domain k8s.baifendian.com
Sep 24 09:05:13 dnsmasq[21]: cleared cache
/entrypoint.sh: line 27: cloud-config-server: not found
/entrypoint.sh: line 15: addons: not found
/entrypoint.sh: line 11: addons: not found
time="2016-09-24T09:05:13Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.1 instance.id=2c3ae4bd-068d-48c9-80a9-a9f1892b9437 version=v2.5.0-rc.1-144-g431cfa3
time="2016-09-24T09:05:13Z" level=info msg="redis not configured" go.version=go1.7.1 instance.id=2c3ae4bd-068d-48c9-80a9-a9f1892b9437 version=v2.5.0-rc.1-144-g431cfa3
time="2016-09-24T09:05:13Z" level=info msg="Starting upload purge in 52m0s" go.version=go1.7.1 instance.id=2c3ae4bd-068d-48c9-80a9-a9f1892b9437 version=v2.5.0-rc.1-144-g431cfa3
time="2016-09-24T09:05:13Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.7.1 instance.id=2c3ae4bd-068d-48c9-80a9-a9f1892b9437 version=v2.5.0-rc.1-144-g431cfa3
time="2016-09-24T09:05:13Z" level=info msg="listening on [::]:5000, tls" go.version=go1.7.1 instance.id=2c3ae4bd-068d-48c9-80a9-a9f1892b9437 version=v2.5.0-rc.1-144-g431cfa3
/entrypoint.sh: line 36: syntax error: unexpected "("
```

**Comment by zhengbo0** [comment]
设置完gopath和goroot环境变量后，把go install 改为go get 就可以安装addons，否则找不到，汗

**Comment by zhengbo0** [comment]
这样修改不知道可以不
```
#!/bin/bash

GO_ENV=$(go env; echo $?)
if [[ $GO_ENV==0 ]]; then
 mkdir work > /dev/null 2>&1 ||  export GO_PATH=$PWD/work
else
 echo "you must install golang environment"
fi

if go get \
      github.com/k8sp/sextant/cloud-config-server \
      github.com/k8sp/sextant/addons; \
then
   cp $GOPATH/bin/{cloud-config-server,addons} .
   docker build -t bootstrapper .
fi
```
@typhoonzero  @cxwangyi

**Comment by wangkuiyi** [comment]
@zhengbo0 你上面贴的这个和 @typhoonzero 的问题没有关系吧？

武毅的问题是[这一行](https://github.com/k8sp/sextant/blob/master/docker/entrypoint.sh#L36):
```
DOCKER_IMAGES=("typhoon1986/hyperkube-amd64:${hyperkube_version}" \
  "typhoon1986/pause:${pause_version}" \
  "typhoon1986/flannel:${flannel_version}" \
  "yancey1989/nginx-ingress-controller:0.8.3" \
  "yancey1989/kube2sky:1.14" \
  "typhoon1986/exechealthz:1.0" \
  "yancey1989/yancey1989/kube-addon-manager-amd64:v5.1" \
  "typhoon1986/skydns:latest");
```
这是因为只有很新版本的bash才支持这种array的定义的语法。实际上，Mac OS X自带的bash都不支持。我是需要用Homebrew安装一个bash才能在我的iMac上执行上述脚本。

我理解最直接的办法是看看有没有bash array之外的其他办法来描述上述功能。

**Comment by wangkuiyi** [comment]
@typhoonzero 贴的信息中有另一个错误
```
/entrypoint.sh: line 36: syntax error: unexpected "("
```
是因为bash需要非常新的版本（更别提golang:alpine里的ash是bash的祖先）才支持bash array。ash是bash的祖先，比最老的bash还要弱。

我想了想，可能最简单的解法是：让 bsroot.sh 生成一个*ash脚本*（注意不是bash脚本） `./bsroot/load-k8s-images.sh`，其中是类似如下彻底展开了的并且符合朴素ash语法的内容：

```
docker load < /bsroot/typhoon1986_pause:1.0.tar
docker tag typhoon1986_pause:1.0.tar bootstrapper:5000/pause:1.0.tar
docker push bootstrapper:5000/pause:1.0.tar
...
```

然后在*笔记本*上执行：

```
scp -r ./bsroot root@bootstrapper:/
ssh bootstrapper -c /bsroot/load-k8s-images.sh
```

**Comment by pineking** [comment]
一种做法是在 alpine 里装上 bash?
https://github.com/yikaus/docker-alpine-bash/blob/master/Dockerfile

**Comment by jiamliang** [comment]
@pineking  +1

**Comment by wangkuiyi** [comment]
@pineking @jiamliang 好主意。我有一个考虑：这样是否没有坚持对技术依赖的“最简单化“的原则？或者说，如果没有bash也可以，是不是就不应该引入bash？

我有一个比较具体的考虑：我之前尝试过用 gcc Docker image来build dnsmasq。最近 @Yancey1989 @typhoonzero 也考虑过用 golang Docker image来build cloud-config-server和addon。如果这样，其实bootstrapper Docker image的base image甚至可以简化为 scratch —— 这是一个空的“虚拟”image，里面什么都没有，既没有ash也没有bash，也没有包管理器可以安装ash或者bash了。

**Comment by typhoonzero** [comment]
not found的问题的解决方法是，在Dockerfile中增加：
```
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
```
Since the musl and glibc so are compatible, you can make this symlink and it will fix the missing dependency.

**Comment by zhengbo0** [comment]
我在Ubuntu上，只需要配置好Go环境，把endpoint.sh中go install 修改go install 修改为go get就可以了，没有其他的报错

**Comment by wangkuiyi** [comment]
刚才会议讨论：

这个问题重新定义为：有几个方法把重要镜像docker push到bootstrapper service里的Docker registry服务：

1. 在*笔记本*上执行docker push
1. 在bootstrapper server上执行docker push
1. 在bootstrapper Docker container里的entrypint.sh里执行docker push

闫旭提醒之前碰到了一个问题：*如果在bootstrapper Docker container里执行docker push，可能container里的Docker 版本和bootstrapper server上的Docker daemon的版本不一致，导致docker push失败*。所以这种选择就放弃了。

在*笔记本*上执行需要等待bootstrapper service启动起来才能做，不如选择第二种方法。

而第二种方法已经在目前的`https://github.com/k8sp/sextant/blob/master/start_bootstrapper_container.sh`里面实现了。所以这个讨论close掉。

**Comment by wangkuiyi** [comment]
我理解如果一个go程序没有依赖cgo，则不应该依赖libc.so。我再看看。

**Comment by wangkuiyi** [comment]
我怀疑是因为cloud-config-server和addons依赖了某个第三方库，从而间接依赖了cgo，导致编译结果依赖libc.so。

为了排查第三方库，我要分析这两个程序共同依赖了哪些第三方库。为此我用了 https://github.com/hirokidaichi/goviz 。因为 https://github.com/hirokidaichi/goviz 和 Go 1.6 有不兼容，所以我沿着其中一个fix PR扎到了 https://github.com/richardwilkes/goviz 。这个是可用的。

执行以下命令，
```
goviz -i github.com/k8sp/sextant/cloud-config-server | dot -Tpng a.png
goviz -i github.com/k8sp/sextant/addons | dot -Tpng b.png
```
得到两个图：

![a](https://cloud.githubusercontent.com/assets/1548775/18901830/1b236c30-8503-11e6-8d02-9e30f65ac5e5.png)

![b](https://cloud.githubusercontent.com/assets/1548775/18901833/1fbaa29a-8503-11e6-87f6-b9e8ed6e2db0.png)
