### ISSUE TITLE
Sextant设计思路梳理

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#225]
## 请大家讨论审阅以下Sextant 工作流程的设计方案

1. 在可以访问外网的*笔记本*或者vm-cluster的*host*上（开发机基本就是host）上做准备工作。这台机器需要：

   1. 安装 Go 编译器：要build Sextant里的Go程序。

   1. 安装 Docker：要 docker pull/build 和 docker save 很多 images。

      【注意1】我之前有一次讨论，说*笔记本*上build Sextant Go程序时，
      不应该用docker image `golang`而应该用本地安装的Go编译器。当时的
      理由是安装Go比安装Docker简单。实际上*笔记本*上反正也需要Docker。
      如果下面设计中的步骤里，用golang image来build Sextant程序，则*笔
      记本*上可以不安装Go。

      ***会议讨论：可以假设笔记本上既有Go也有Docker。***
   
   准备工作流程如下：
   
   1. 配置 Go 环境
      ```
	  mkdir -p ~/work
      export GOPATH=$HOME/work
	  ```

   1. 获取Sextant并且获取其中Go程序的依赖

      ```
	  go get https://github.com/k8sp/sextant/
	  ```
   1. 编辑 `~/cluster-desc.yml` 描述即将安装的机群

   1. 下载相关文件，生成 `./bsroot` 目录

      ```
	 cd $GOPATH/src/github.com/k8sp/sextant
      ./bsroot.sh ~/cluster-desc.yml
	  ```

      【注意2】：这一步包括了调用
      `$GOPATH/src/github.com/k8sp/sextant/docker/build.sh`来编译
      Sextant里的Go程序，并且docker build bootstrapper image。所以
      bootstrapper image不需要基于 `golang:alpine`，而只需要基于
      `alpine`（alpine支持安装dnsmasq）。

      ***会议讨论：确实只需要alpine，应该不需要golang:alpine了。***
     
   1. 把准备好的内容上传到 bootstrapper server（或者bootstrapper VM）：

      ```
      scp -r ./bsroot root@bootstrapper:/
      ```

1. 在 bootstrapper server（或者bootstrapper VM）上启动 bootstrapper service：

   ```
   host $ ssh bootstrapper
   bootstrapper $ docker load /bsroot/bootstrapper.tar
   bootstrapper $ docker run -d ... bootstrapper
   ```

   为了让bootstrapper service中的Docker registry service能向Kubernetes
   机群提供服务，还需要向其中push一些必须的images。
 
   ```
	DOCKER_IMAGES=("typhoon1986/hyperkube-amd64:${hyperkube_version}" \
	  "typhoon1986/pause:${pause_version}" \
      ...);
	len=${#DOCKER_IMAGES[@]}
	for ((i=0;i<len;i++)); do
	  DOCKER_IMAGE=${DOCKER_IMAGES[i]}
	  DOCKER_TAR_FILE=...
	  DOCKER_TAG_NAME=...
	  docker load < $DOCKER_TAR_FILE
	  docker tag $DOCKER_IMAGE $DOCKER_TAG_NAME
	  docker push $DOCKER_TAG_NAME
	done
   ```

   【注意3】这段代码里使用了bash的array功能，不能在老版本的bash（比如
   MacOSX自带的）或者ash（bootstrapper的base image自带的）里执行。一个
   解决方法是，上述代码由`bsroot.sh`生成，把`for`循环展开成为朴素ash语
   法，并且以`load-k8s-images.sh`的形式写入`./bsroot`，随后在笔记本上
   执行。详
   见[这里](https://github.com/k8sp/sextant/issues/224#issuecomment-249429285)。

   或者写入 `entrypoint.sh`，并经由`docker build bootstrapper`称为
   bootstrapper image的一部分。注意`docker build bootstrapper`这个命令
   也是`bsroot.sh`执行的。

   另一个办法是在bootstrapper image里安装bash。详
   见[这里](https://github.com/k8sp/sextant/issues/224#issuecomment-249430319)。

   ***会议讨论，docker push应该在bootstrapper server上执行。 @Yancey1989 已经通过 https://github.com/k8sp/sextant/pull/220 增加了 start_bootstrapper_container.sh  来做这个工作。***

**Comment by typhoonzero** [comment]
not found的问题的解决方法是，在Dockerfile中增加：
```
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
```
Since the musl and glibc so are compatible, you can make this symlink and it will fix the missing dependency.

**Comment by typhoonzero** [comment]
对于最终用户来说，前面的配置go环境步骤都可以不需要，用户可以直接docker pull我们使用dockerhub自动编译的docker image直接使用就好。

最简单的用户使用的流程：

1. git clone或直接在github.com下载release.tar.gz
1. 配置cluster-desc.yml
1. ./bsroot.sh cluster-desc.yml
1. [可选] 拷贝到bootstrapper server
1. ./start_bootstrapper.sh(包含docker run, docker push等)

**Comment by jiamliang** [comment]
@typhoonzero 我刚刚跟 @Yancey1989 讨论完。
我们应该提供一个“开箱即用”的版本。让用户只需要点击一个shell脚本，就开始引导用户去配置机群的配置文件，当用户点击“确认”的时候，喝一杯咖啡等着一切都ok就可以了。
我们不需要go环境，不需要各种docker pull 、save等操作。

**Comment by jiamliang** [comment]
当然，我们还可以这样，提供一个配置文件的定制页面，让用户在上面填好了，（还可以让用户勾选他所需要的image等等），然后点击下载，就可以得到他对应的个性化版本。

**Comment by wangkuiyi** [comment]
在会议上大家讨论后，更新了上面的issue描述。三个主要问题都已经有答案或者action items了。其中问题2的讨论决议创建issue https://github.com/k8sp/sextant/issues/236
