### ISSUE TITLE
Can't mount hosts's folder in vagrant VM via NFS

### ISSUE THREAD

**Issue by lipeng-unisound** [k8sp/sextant#228]
In branch vm-cluster, when I `vagrant up bootstrapper`, I got the following error
```
==> bootstrapper: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'nolock,vers=3,udp' 172.28.128.1:'/Users/li/go/src/github.com/k8sp/sextant/bsroot' /bsroot

Stdout from the command:



Stderr from the command:

mount.nfs: access denied by server while mounting 172.28.128.1:/Users/li/go/src/github.com/k8sp/sextant/bsroot
```

After some check, I guess the cause of this issues is: The bootstrapper VM has two network interfaces, one with static IP address and one dynamic. When the VM is being `vagrant up`ed, the static IP address is written to host's /etc/exports, but after the VM is booted, it mounts host's NFS exported folder via the other network interface.

My host OS is macOS Sierra  10.12.1.

**Comment by zhengbo0** [comment]
主要原因是该vm有两个private_network网卡，一个是hostonly（dhcp）,一个是virtualbox__intnet(static ip)，hostonly通过dhcp获取的ip地址为172.28.128.1
实际写入/etc/exports文件的
```
"/home/zhengbo/k8sp/sextant/bsroot" 192.168.8.101(rw,no_subtree_check,all_squash,anonuid=0,anongid=0,fsid=1462005517)
```
ip地址不同，导致访问拒绝，目前修改办法为：通过把Vagrantfile文件中
```
bs.vm.network "private_network",  type:" dhcp",  :adapter=>3
```
修改为
```
bs.vm.network "private_network", ip: "192.168.8.102", :adapter=>3
```

**Comment by wangkuiyi** [comment]
请 @lipeng-unisound 升级一下 VirtualBox，再试试。和 @JunfeiYang 沟通。

**Comment by JunfeiYang** [comment]
我这边，升级完毕；可以挂载

**Comment by lipeng-unisound** [comment]
升级 Vagrant 版本至 1.8.6，VirtualBox 版本至 5.1.6 后，问题解决。
