### ISSUE TITLE
start_bootstrapper_container.sh 不能指定自定义的bsroot目录

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/sextant#230]
start_bootstrapper_container.sh 不能指定自定义的bsroot目录

现在是直接使用：`-v /bsroot:/bsroot`挂载的。但目前的bsroot.sh生成的目录并非固定在/bsroot

**Comment by wangkuiyi** [comment]
start_bootstrapper_container.sh加一个参数，指定bootstrapper server上的bsroot目录所在地。如果没有指定，则默认是 /bsroot。
