### ISSUE TITLE
Sextant的unit test

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#239]
和 @typhoonzero 讨论了一下，vm-cluster是Sextant的regression test，此外还需要unit test。比如检查bsroot.sh生成的目录和文件是否都在。

一方面，需要拆分出应该被unit test的每个“单元”，比如bsroot里定义的每个bash函数。此外，还有其他几个重要的bash程序。

另一方面，要能用TravisCI执行这些unit test。需要研究一下 https://docs.travis-ci.com/user/customizing-the-build

**Comment by typhoonzero** [comment]
我会在 https://github.com/k8sp/sextant/issues/207 完成之后，逐步补充没部分的单元测试

**Comment by wangkuiyi** [comment]
我来用 https://code.google.com/archive/p/shunit2/ 先对bsroot.sh写一个unit test试试。也看看Travis CI如何跑shell unit test。

**Comment by Yancey1989** [comment]
找到了一个在travis-ci中使用bats的demo:https://github.com/tkuchiki/bats-travis-ci，但有一个问题：由于目前sextant使用的语言是golang，貌似travis-ci目前还无法支持多语言，还要继续再调研一下：https://github.com/travis-ci/travis-ci/issues/4090
