### ISSUE TITLE
bootstrapper 启动后cloud-config-server 运行失败

### ISSUE THREAD

**Issue by JunfeiYang** [k8sp/sextant#242]
## 描述
在vm cluster 测试中 bootstrapper up 完成后，vagrant ssh bootstrapper
登陆到 bootstrapper中，发现cloud-config-server 没有运行
<img width="1156" alt="2016-09-28 10 01 41" src="https://cloud.githubusercontent.com/assets/16366286/18898204/9c8a75ca-8562-11e6-8f40-64da8be9c2d9.png">

使用 docker exec -it 74c /bin/bash 执行 cloud-config-server命令
<img width="1426" alt="2016-09-28 9 55 55" src="https://cloud.githubusercontent.com/assets/16366286/18898224/c406f56a-8562-11e6-8855-9cb358b3027a.png">

出现以下错误：
bash: /go/bin/cloud-config-server: cannot execute binary file: Exec format error

## 在 mac os x 上查看 依赖的库
<img width="1128" alt="2016-09-28 11 20 29" src="https://cloud.githubusercontent.com/assets/16366286/18899717/9ca08ddc-856d-11e6-83e2-d5c6d8c11ad8.png">

**Comment by wangkuiyi** [comment]
不好意思，这是因为在mac下运行build.bash的时候，生成的是mac的mach-o格式的binary file，不能在Linux上运行。

怪我写build.bash的时候犯了低级错误，没有用cross-compilation。这就修改。
