### ISSUE TITLE
pxe 自动安装coreos异常

### ISSUE THREAD

**Issue by zhengbo0** [k8sp/sextant#243]
现在只能内存安装coreos，硬盘安装失败，检查发现上面的异常
![qq 20160928100231](https://cloud.githubusercontent.com/assets/14144704/18898675/af651206-8565-11e6-8b91-ea76043a4046.png)
手动执行下面两行可以在硬盘成功安装coreos，奇怪
```
wget -O ${mac_addr}.yml http://192.168.8.101/cloud-config/${mac_addr}
sudo coreos-install -d /dev/sda -c ${mac_addr}.yml -b http://192.168.8.101/static -V current && sudo reboot

```

**Comment by typhoonzero** [comment]
/dev/sda文件存在么？
