### ISSUE TITLE
提醒：获取sextant的方式需要省略号：go get github.com/k8sp/sextant/...

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#247]
之前 @lipeng-unisound  @zhengbo0 等兄弟好像问过为什么 `go get github.com/k8sp/sextant` 不能编译 cloud-config-server和addon程序，而且没有分析这两个程序的依赖并且自动下载这些依赖。

这是因为 sextant目录里没有 Go源码文件，而且我们需要build的Go程序在sextant的子目录里（cloud-config-server和addon），所以需要省略号：

```
go get github.com/k8sp/sextant/...
```

**Comment by lipeng-unisound** [comment]
学习了，谢谢！

**Comment by wangkuiyi** [comment]
我来把这一行加入到design doc里。
