### ISSUE TITLE
Add sudo before docker command

### ISSUE THREAD

**Issue by lipeng-unisound** [k8sp/sextant#258]
在多数系统中（我目前知道的仅有 CoreOS 例外），普通用户无法执行 `docker` 命令（将普通用户加入 docker 组可以无需 sudo，但是这时用户拥有了 root 权限，所以我个人不喜欢这种做法）。所以，要么脚本中的 docker 命令前边都加上 sudo，要么就在 README.md 里写明脚本需要由 root 用户执行或者普通用户使用 sudo 执行。

现在 README.md 里的需要满足的条件中『拥有 bootstrapper server 的 root 权限』，没有说明上面的问题。

**Comment by wangkuiyi** [comment]
明白了。我恰好在 https://github.com/k8sp/sextant/pull/254 里修改 sextant-design.md。我在文档里加上说明吧。
