### ISSUE TITLE
docker/build.sh 执行中出现 No space left on device 错误

### ISSUE THREAD

**Issue by lipeng-unisound** [k8sp/sextant#262]
![image](https://cloud.githubusercontent.com/assets/17057205/18942736/821a03d6-864d-11e6-9e51-4fb4bd70dc3d.png)

Environment:
CentOS Linux release 7.2.1511 (Core)
Docker version 1.12.1, build 23cf638

**Comment by wangkuiyi** [comment]
@lipeng-unisound 是不是因为这个CentOS机器上确实就没有空间了呢？用`df`看看？

**Comment by lipeng-unisound** [comment]
有空间的。我在我的 MacBook Pro 上以及跑在上面的虚拟机上也没遇到过这个问题。超出我的知识能理解的范围了。

**Comment by wangkuiyi** [comment]
@lipeng-unisound 我搜了一下，有几个可以尝试的方案：

1. http://stackoverflow.com/a/30605040/724872 里说:

   > Check that you have free space on /var as this is where Docker stores the image files by default (in /var/lib/docker).

**Comment by typhoonzero** [comment]
@lipeng-unisound  is this fixed, please close this issue if it is already fixed. Or you can comment for update.
