### ISSUE TITLE
kubectl连接apiserver时，报tls异常

### ISSUE THREAD

**Issue by zhengbo0** [k8sp/sextant#282]
```
bootstrapper bsroot # ./kubectl get node
Unable to connect to the server: x509: certificate is valid for 10.100.0.1, not 10.10.10.208
```
https://github.com/k8sp/sextant/blob/master/cloud-config-server/certgen/certgen.go#L28
中需要配置k8s master的ip地址，如果master有多台，需要配置为代理的地址
```
IP.2 = ${MASTER_HOST}
```
这个IP.1的值可以从cluster-desc.yml读取

**Comment by pineking** [comment]
IP.1 和 IP.2 是不是留一个配置为代理的地址就可以了？

**Comment by zhengbo0** [comment]
IP.2 可以设置为代理IP，我尝试了用k8s master的主机名，也就是mac地址设置，导致bootstrapper vm无法 ssh master vm上，可能有异常

**Comment by pineking** [comment]
@zhengbo0 你这修改的不是 k8s 相关的配置吗？ 怎么会影响机器之间的 ssh？

**Comment by Yancey1989** [comment]
@pineking 
> IP.1 和 IP.2 是不是留一个配置为代理的地址就可以了？

这个是不行的，IP.1配置的是apiserver的ClusterIP，在Kubernetes集群中运行的pod都是通过这个ClusterIP来连接的apiserver。

@zhengbo0 
```IP.{num}``` 这个字段只能配置IP的格式，主机名需要在```DNS.{num}```这个字段下进行配置

**Comment by pineking** [comment]
@Yancey1989 对的，是需要在 DNS 下配置，要解析下

**Comment by Yancey1989** [comment]
已经在 https://github.com/k8sp/sextant/pull/277 这个PR里将kubectl的HTTPS连接方式改为HTTP，所以应该已经不存在 @zhengbo0 提出的这个问题了。
