### ISSUE TITLE
build bootstrapper image失败没有提示信息

### ISSUE THREAD

**Issue by jiamliang** [k8sp/sextant#292]
在bsroot.sh中，build bootstrapper image的时候，由于没有找到go （使用sudo了）导致build  bootstrapper image这个过程失败了，但是提示信息中并没有显示失败，仍然提示 Done

**Comment by pineking** [comment]
建议在 https://github.com/k8sp/sextant/blob/master/bsroot.sh#L46 `check_prerequisites` 里加入 go 命令是否存在的检测

**Comment by wangkuiyi** [comment]
青松补充问题描述：docker/build.sh 在build失败的时候也显示Done。
