### ISSUE TITLE
建议在 build bootstrapper image 之前，删除掉已经存在的（之前生成过的）build bootstrapper image

### ISSUE THREAD

**Issue by jiamliang** [k8sp/sextant#293]
在issue https://github.com/k8sp/sextant/issues/292 中提到：在 build bootstrapper image 过程中失败了，依然提示Done. 
在后续执行 docker save 的时候，其实是将之前生成的bootstrapper image save到了本地，但这个image并不是最新的，但通过查看时间戳还是最新的时间，对于诊断问题带来了迷惑和干扰。

**Comment by wangkuiyi** [comment]
#292 fix 之后，这个就不用fix了。

**Comment by wangkuiyi** [comment]
#292 fix 之后，这个就不用fix了。
