### ISSUE TITLE
使用最新的sextant代码在vm中测试，worker节点安装coreos失败

### ISSUE THREAD

**Issue by zhengbo0** [k8sp/sextant#312]
![qq 20161017102953](https://cloud.githubusercontent.com/assets/14144704/19423833/cd9308d2-9456-11e6-8d47-790aa06ed9d8.png)

**Comment by zhengbo0** [comment]
![qq 20161017105856](https://cloud.githubusercontent.com/assets/14144704/19424067/c7805ab0-9458-11e6-96f4-ec800f05760a.png)

**Comment by typhoonzero** [comment]
Notice the line "137GB/128GiB", will check install process later

**Comment by zhengbo0** [comment]
![qq 20161017141415](https://cloud.githubusercontent.com/assets/14144704/19427432/885dc3e0-9476-11e6-95a8-70298fc9627c.png)

**Comment by zhengbo0** [comment]
![qq 20161017143154](https://cloud.githubusercontent.com/assets/14144704/19427445/914360dc-9476-11e6-8619-b40cabf523ee.png)

**Comment by zhengbo0** [comment]
经过排查，coreos已经成功安装，安装的位置是/dev/sda，由于sda 不是硬盘的启动第一块盘。所以导致系统无法从硬盘启动。当把添加的ide类型的硬盘删除，系统可以正常启动了。

**Comment by Yancey1989** [comment]
我在Mac系统下没有复现额，是Linux才会有这个问题么？

**Comment by typhoonzero** [comment]
今天测试遇到的问题：Mac下，在安装worker节点时，master会持续写盘。导致宿主机也会僵死。

**Comment by zhengbo0** [comment]
@ Yancey1989  目前来看，在mac下没有问题，在Ubuntu下存在这个问题

**Comment by wangkuiyi** [comment]
@Yancey1989 和 @JunfeiYang 用host的都是mac，没有遇到这个问题。

@zhengbo0 用的是ubuntu host， 碰到了这个问题。

@typhoonzero 用的是mac host，也碰到了这个问题。

有可能和VirtualBox相关
