### ISSUE TITLE
执行kubectl get node 时no such host

### ISSUE THREAD

**Issue by JunfeiYang** [k8sp/sextant#321]
## 描述

在vm cluster测试完成后，需要使用kubectl 测试集群基础服务是否正常时，出现了下面的问题：
<img width="823" alt="2016-10-17 3 22 41" src="https://cloud.githubusercontent.com/assets/16366286/19429083/58574b62-9480-11e6-85c2-09964721a647.png">

查看了下面的系统配置
<img width="668" alt="2016-10-17 3 23 51" src="https://cloud.githubusercontent.com/assets/16366286/19429093/627e4db6-9480-11e6-9122-fb47671b9fb7.png">
<img width="649" alt="2016-10-17 3 25 42" src="https://cloud.githubusercontent.com/assets/16366286/19429577/f2137602-9482-11e6-8d2f-a16c810d7528.png">
<img width="396" alt="2016-10-17 3 27 02" src="https://cloud.githubusercontent.com/assets/16366286/19429581/f9fd6a58-9482-11e6-9294-69cdc7430874.png">

**Comment by typhoonzero** [comment]
I usually modify /etc/resov.conf manually to fix this.

**Comment by Yancey1989** [comment]
```echo "domain {{domainname}}" >> /etc/resov.conf``` will fix this issue.Maybe this operation can  be written in start_bootstrapper_container.sh, I'll try this.

**Comment by pineking** [comment]
没看懂，nslookup master/worker 是什么意思？2d-a1 这个 hostname 为什么没查询到？

**Comment by zhengbo0** [comment]
/etc/resov.conf写入的内容（search k8s.baifendian.com），被vm启动时给覆盖掉了，无法解析主机名

**Comment by Yancey1989** [comment]
将dns信息在 ```provision_bootstrapper_vm.sh```中写入，发现是可行的。辛苦 @zhengbo0 帮忙Review 下 #323

**Comment by JunfeiYang** [comment]
@pineking  nslookup master/worker 是为了验证k8s集群里的dns是否可以正常解析。
