### ISSUE TITLE
借几台笔记本电脑和一个家用路由器，测试Sextant

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#330]
再加一个物理机群来做验证看来很必要：

- 如果新的机群里没有发现 https://github.com/k8sp/sextant/issues/317 描述的问题，那么我们可以打0.2 tag了。
- 如果发现了同样的问题，多一份复现就可能进一步缩小了问题的调查范围。

建议用笔记本电脑来尝试有两个好处：

- 一方面是为了demo方便，别让这个努力只是“复现一个issue中的问题”，而是还可以在demo中重用。笔记本电脑加一个家用路由器的配置很简单
- vm-cluster 是用VM模拟物理机来做验证，万一VM就是“不足够像”物理机，那就让人很不放心了。

**Comment by Yancey1989** [comment]
借到了5台笔记本（3*ThinkPad T440， 2*Thinkpad X240）+一个交换机

**Comment by JunfeiYang** [comment]
已经测试完毕，测试已经通过。
![wechatimg17](https://cloud.githubusercontent.com/assets/16366286/19636863/6e91161e-99fe-11e6-8880-30aa67aca4ed.jpeg)
![wechatimg16](https://cloud.githubusercontent.com/assets/16366286/19636868/73643842-99fe-11e6-8542-a6f21e98122d.jpeg)
![wechatimg18](https://cloud.githubusercontent.com/assets/16366286/19636870/772b0c30-99fe-11e6-9421-8d627450f354.jpeg)
