### ISSUE TITLE
template 文件区别

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#335]
https://github.com/k8sp/sextant/blob/master/vm-cluster/cluster-desc.yml.template
https://github.com/k8sp/sextant/blob/master/cloud-config-server/template/cluster-desc.sample.yaml

这两个 template 有什么区别吗？需要维护两套 template？

**Comment by zhengbo0** [comment]
cluster-desc.yml.template是写好的在vm-cluster上测试用的模板文件，让客户无需修改模板文件的情况下，或者不了解模板文件如何配置的情况下，启动k8s环境进行测试

**Comment by pineking** [comment]
@zhengbo0 明白了，多谢解释，我意思是能不能只保留一个，也能满足在虚拟机里直接跑，客户可以不用了解模板文件如何配置

**Comment by zhengbo0** [comment]
可以共用一个模板文件，分开的意义主要是为了保持彼此独立，修改时互不影响
物理机器部署k8s集群中，那个配置cluster-desc.sample.yaml是必须手动修改的，给的模板是多台配置
虚拟机环境中模板文件比较固定，给的模板是单台配置

**Comment by pineking** [comment]
嗯，一般物理机和虚拟机都会 `cp xxxxx.sample.yaml xxxxx.yaml` ，然后在 xxxxx.yaml 里改。
两个 yaml template 文件都保留也没关系，我先 close 这个 issue。
