### ISSUE TITLE
bsroot.sh: Building addons...# net exec: "gcc": executable file not found in $PATH Failed

### ISSUE THREAD

**Issue by jiamliang** [k8sp/sextant#339]
bsroot.sh执行过程中报错：
``` shell
Building addons...# net
exec: "gcc": executable file not found in $PATH
Failed
```
在[bsroot.sh#L344](https://github.com/k8sp/sextant/blob/master/bsroot.sh#L344) 缺少下面的环境变量：
``` shell
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 
```
类似于 [bsroot.sh#L257](https://github.com/k8sp/sextant/blob/master/bsroot.sh#L257)

**Comment by pineking** [comment]
PR #338 已修复
