### ISSUE TITLE
在程序中增加对 cluster-desc.yaml 、cloud-config.yaml等yaml文件合法性的检测

### ISSUE THREAD

**Issue by jiamliang** [k8sp/sextant#341]
1. 由于cluster-desc.yaml是需要最终用户根据自身的环境进行配置的，那么这个yaml文件的格式就不一定合法。如果这个配置文件的格式有问题，在解析yaml的时候就会出错。
2. 根据cluster-desc.yaml和template生成的cloud-config.yaml 或者其他配置文件的格式也需要进行校验。这些yaml格式有问题的话，用户不一定能看到错误信息。

昨天我在增加一个公钥到cluster-desc.yaml，少写了一个空格，结果在安装coreos 的时候，pxe引导完了之后就卡住了。多亏@lipeng-unisound和@pineking的帮助，终于从坑里爬出来了。

**Comment by typhoonzero** [comment]
昨天和闫旭也讨论了是否要在config.go中增加一个validate函数，验证解析后的配置是否合法。这么说同时也要验证yaml本身是否能被解析。这样在cc server启动的时候如果yaml解析失败则报错退出，docker run失败

**Comment by typhoonzero** [comment]
按照刚才的讨论，问题是：

cc server根据cluster-desc生成的cloud-config（通过http返回的字符串）是非法的yaml，这样会直接导致无法安装coreos到硬盘。

所以应该在执行bsroot.sh的时候，就尝试执行一些把cluster-desc和cloud-config.template整合并验证，类似单元测试

**Comment by jiamliang** [comment]
剽窃来的：
$ cat yamltest.txt| python -c 'import yaml,sys;yaml.safe_load(sys.stdin)'
如果抛出异常，表明yaml不合法，如果返回值是0，证明是合法的。
原文：http://www.opensourcerers.org/short-tip-verify-yaml-in-shell-via-python-one-liner/

**Comment by typhoonzero** [comment]
这样也会依赖python，而且生成cloud-config yaml文件的逻辑也需要能单独执行才可以在bsroot.sh中完成验证。仍然需要一个测试的程序。

刚和 @Yancey1989 讨论，可以在cloud-config-server程序增加一个参数-validate，如果指定这个参数则只做验证，如果不指定就启动cloud-config-server。这样就可以在bsroot.sh中，编译好cloud-config-server(local arch)，然后执行validate，判断cluster-desc和cloud-config.template组合生成的结果是否正确

**Comment by Yancey1989** [comment]
建议验证的内容包括：

1. cluster-desc是否符合YAML文件的格式要求，有特殊要求的value是否符合要求
2. 至少对cluster-desc中配置的几个MAC生成的cc文件做格式合法性验证。
