### ISSUE TITLE
安装 CoreOS 时，可以指定 CoreOS 版本号和配置是否自动更新 CoreOS

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#345]
原因：
由于 CoreOS 版本更新较快， 而 Nvidia 驱动的更新有可能赶不上 CoreOS 的 Linux kernel 的更新。
导致编译 Nvidia GPU 驱动时，编译不通过。

需求：
1. 在集群安装的时候，cluster-describle.yaml 配置中可以指定 CoreOS 版本号
2. 在集群 cluster-describle.yaml 配置中可以配置是否开启/关闭 CoreOS 自动更新

**Comment by pineking** [comment]
提醒下：

当指定 CoreOS 版本号为 A 时，对应的 PXE image 也需要相应的切换为 A
目前 CoreOS 镜像和 PXE 镜像是存储在不同目录下，是不是重新组织下，一次性切换较好

**Comment by JunfeiYang** [comment]
准备修复

**Comment by Yancey1989** [comment]
配置CoreOS版本号的这个feature和 #351 这个需求有相同的地方，我在 PR: #372 中增加了这个功能，请 @JunfeiYang 帮忙Review这部分代码，如果没问题可以再创建一个PR来完成配置自动更新的部分。

**Comment by JunfeiYang** [comment]
@Yancey1989 ,好的
