### ISSUE TITLE
自动加载 GPU 驱动

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#346]
需求：
对于集群中 GPU 机器， 在 cluster-description.yaml 里在 hostname 下添加 `setup_gpu: y` 选项，实现自动加载 GPU 驱动

实现：
- 事先编译好的GPU 驱动，工具，动态库：module.tar.bz2 tool.tar.bz2 libraies.tar.bz2
- 脚本参考：https://github.com/k8sp/k8s-tensorflow/tree/master/load_gpu_drivers

**Comment by typhoonzero** [comment]
需要在cc中加入自动加载驱动的相关配置。
