### ISSUE TITLE
cluster-desc.yml中的配置信息 osd_journal_size: 5000 在安装ceph 的时候，并不起作用。

### ISSUE THREAD

**Issue by jiamliang** [k8sp/sextant#347]
在cluster-desc.yml中配置了 osd_journal_size: 5000 ，期望在安装ceph_osd的时候，将journal的分区大小调整为5G，但在实际安装的过程中，journal的分区大小仍未100M

cluster-desc.yml中的配置信息：
``` shell
ceph:
  zap_and_start_osd: y
  osd_journal_size: 5000
```

下面是一台GPU机器安装完成之后的分区信息：
``` shell
core@0c-c4-7a-82-c5-bc ~ $ lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 119.2G  0 disk s = true
|-sda1   8:1    0   128M  0 part /boot
|-sda2   8:2    0     2M  0 part 
|-sda3   8:3    0     1G  0 part s = false
|-sda4   8:4    0     1G  0 part /usr
|-sda6   8:6    0   128M  0 part /usr/share/oem
|-sda7   8:7    0    64M  0 part 
`-sda9   8:9    0 116.9G  0 part /
sdb      8:16   0   1.8T  0 disk 
|-sdb1   8:17   0   1.8T  0 part 
`-sdb2   8:18   0   100M  0 part 
sdc      8:32   0   1.8T  0 disk 
|-sdc1   8:33   0   1.8T  0 part 
`-sdc2   8:34   0   100M  0 part 
sdd      8:48   0   1.8T  0 disk 
|-sdd1   8:49   0   1.8T  0 part 84L, 1963C
`-sdd2   8:50   0   100M  0 part 
```

**Comment by pineking** [comment]
@jiamliang 家盟你把原因也说下吧

**Comment by typhoonzero** [comment]
应该是bug，我处理吧

**Comment by typhoonzero** [comment]
使用master最新的代码，配置cluster-desc中`osd_journal_size: 5000`，执行bsroot.sh，执行成功后查看`$BSROOT/html/static/ceph/install-mon.sh`包含已经配置好journal_size是5000的脚本:
```
 23 if [ $? -ne 0 ]; then
 24   echo "Enable cephx."
 25   docker run --rm --net=host \
 26     --name ceph_kvstore \
 27     -e CLUSTER=$CEPH_CLUSTER_NAME \
 28     -e KV_TYPE=etcd \
 29     -e KV_IP=127.0.0.1 \
 30     -e KV_PORT=2379 \
 31     -e OSD_JOURNAL_SIZE=5000 \
 32     --entrypoint=/entrypoint.sh \
 33     "$docker_hub"typhoon1986/ceph-daemon:tag-build-master-jewel-ubuntu-14.04-fix370 populate_kvstore
 34 fi
```

**Comment by pineking** [comment]
@typhoonzero  `-e OSD_JOURNAL_SIZE=5000` 这个环境变量 populate_kvstore 不会读取的，参照 https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L173 我们需要定义一个 ceph.defaults ，映射到 container 里，才能生效写入 etcd， @jiamliang 之前搞过

**Comment by jiamliang** [comment]
正如 @pineking 所说，这个是ceph docker 的一个bug，由于ceph docker里面的ceph.defaults配置文件里面定义的OSD_JOURNAL_SIZE大小，刚好是100M，在启动起来的时候，写到etcd里面去了。我们在install-mon.sh里面写的环境变量，实际上并没有读取。所以，我们看到的现象，就是journal之分了100M的空间，和我们之前在VM-Clouster中配置的大小刚刚好是一致的，这只是巧合而已（无巧不成书）。
解决办法是：我们自己提供一个 ceph.defaults 配置文件，通过 -v 参数，映射到docker里面，覆盖docker自带的ceph.defaults。

**Comment by typhoonzero** [comment]
太巧了。。。我看看
