### ISSUE TITLE
使用物理机测试sextant出现的问题

### ISSUE THREAD

**Issue by JunfeiYang** [k8sp/sextant#348]
## 环境

| 型号 | CPU | 内存 | 硬盘 | 角色 | 备注 |
| --- | :-- | :-- | :-- | :-- | :-- |
| Thinkpad x240 | Intel i3-4030u | 8GB | 500GB | bootstrapper | 1台 |
| Thinkpad x240 | Intel i3-4030u | 8GB | 500GB | master | 1台 |
| Thinkpad T440 | Intel i5-4200u | 4GB | 500GB | worker | 2台 |
## 描述

由于网络原因，下载镜像非常缓慢，执行go get github.com/k8sp/sextant/... 失败
采用拷贝已经测试通过机器(192.168.8.101)上的bsroot目录到192.168.2.10(bootstrapper)机器上进行测试，通过测试，目前发现以下问题：
1.worker wget 无法获取cc配置文件：wget cc 服务配置文件的url 使用的是8081端口；
2.bootstrapper ip: install.sh 这个脚本bootstrapper ip还是192.168.8.101；
3.tftp配置：在master安装后，下载coreos镜像url，还是从192.168.8.101地址进行下载，导致安装失败；
4.ssh key：master获取boostrapper key不是现有机器的key,而是原理机器的key(需要readme更新)
5.Readme 需要更新；

**Comment by pineking** [comment]
代码是最新的吗？

**Comment by jiamliang** [comment]
是不是cluster-desc.yml配置文件需要改一下？
另外，修改yaml文件，是不是需要重新执行 bsroot.sh ? 因为有些配置文件是在 bsroot.sh里面生成的。
检查一下 $bsroot/config 下面的配置文件，是不是都是自己预期的。

**Comment by JunfeiYang** [comment]
不好意思，是我测试的时候的问题。按照readme流程现在完全可以了。我这边已经在笔记本上，测试通过了。

**Comment by jiamliang** [comment]
问题出在哪里？描述一下，以后可以避免。

**Comment by JunfeiYang** [comment]
bootstrapper机器没有互联网访问，/bsroot目录从mac上传到boostrapper server
cluster-desc.sample.yaml 没有修改成bootstrapper 所需的ip和网段
也没有在mac上执行./bsroot.sh cloud-config-server/template/cluster-desc.sample.yaml

**Comment by JunfeiYang** [comment]
## 通过大家的帮助，认真的阅读ReadMe物理机验证通过。
