### ISSUE TITLE
可以在cluster-desc中配置哪些机器不启动ceph osd

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/sextant#349]
目前的开关只是整体打开或者关闭 ceph，需要能指定哪些单独的机器不启动osd，不格式化磁盘，其他的机器默认完成格式化和启动osd。

**Comment by jiamliang** [comment]
这个是 https://github.com/k8sp/sextant/issues/350 的补集，我已经在上面 comment 了

**Comment by typhoonzero** [comment]
之后跟进 #350 吧。我关闭本issue了
