### ISSUE TITLE
单词拼写错误

### ISSUE THREAD

**Issue by HouLinwei** [k8sp/sextant#358]
file: start_bootstrapper_container.sh
line: 6 
detail: start_bootstrapper_contaienr.sh -> start_bootstrapper_container.sh

**Comment by Yancey1989** [comment]
可以直接用超链接来标识https://github.com/k8sp/sextant/blob/master/start_bootstrapper_container.sh#L6

**Comment by wangkuiyi** [comment]
https://github.com/k8sp/sextant/pull/368
@Yancey1989 @HouLinwei Please review!
