### ISSUE TITLE
重新 build Bootstrapper image 并重启 Bootstrapper container，dnsmasq 原来记录的域名信息全部丢失

### ISSUE THREAD

**Issue by jiamliang** [k8sp/sextant#363]
重新build Bootstrapper image 并重启Bootstrapper container，dnsmasq 原来记录的域名信息全部丢失。
机群中已经启动的机器，主机名到ip地址的映射信息丢失。
建议 将 dnsmasq.lease 所在的路径  使用 -v 挂载到本地物理机。

**Comment by pineking** [comment]
原因：

信息记录在 container 的 /var/lib/misc/dnsmasq.conf 文件中，只要而且只有 containter id 不变的情况下，信息才会保留，所以：

* 当 docker restart containter 时，信息不丢失
* 当 docker build image，然后启动 container 时，信息丢失
* 当 docker rm 然后再 start 时，信息丢失

**Comment by JunfeiYang** [comment]
当我们进行docker build image， docker rm 然后再 start 时需要触发一个服务进行更新吗？

**Comment by pineking** [comment]
@JunfeiYang 更新什么？

**Comment by JunfeiYang** [comment]
重新 build Bootstrapper image 并启动 Bootstrapper container，dnsmasq 原来记录的域名信息全部丢失，我们可以再次把域名信息重新加载吗？

**Comment by wangkuiyi** [comment]
是不是需要把container里的`/var/lib/misc/`搞成实际上是映射自host上的某个目录？

**Comment by JunfeiYang** [comment]
这个比较靠谱。

**Comment by pineking** [comment]
重启 dnsmasq 可以重新加载 lease file，使得修改生效。

>The lease file only gets read when dnsmasq starts up: after that it uses an in-memory copy of the data,
which gets written back to the file when it changes.
