### ISSUE TITLE
集群安装时自动配置 harbor 证书

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#373]
需求：
在集群节点安装时，自动配置 harbor 证书，替代手工配置。

方案：
目前有一个 bash 脚本，可以一键运行，只需要在CoreOS 安装后，自动运行此脚本。
参照 https://github.com/k8sp/k8s-tensorflow/tree/master/harbor

**Comment by typhoonzero** [comment]
根据和 @pineking 的讨论，决定使用在k8s集群上提交应用的方式完成habor的安装和部署，包括以下步骤：

1. 在sextant项目增加habor的addon的yaml文件，并根据cluster-desc自动生成habor的配置信息
1. 配置harbor的ssl证书
1. master启动的时候就会自动把habor提交称为集群服务
