### ISSUE TITLE
CoreOS 替换成 CentOS ，能否实现平滑安装

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#375]
需求：
CoreOS 替换成 CentOS

可能的问题：
1. PXE 安装问题不大
2. CentOS 安装完毕后能否正常执行后续的 k8s 和 ceph 流程

**Comment by wangkuiyi** [comment]
是不是要做的事情包括：

1. 要能在 cluster-desc.yaml 里选择操作系统是CentOS还是CoreOS。
1. bsroot.sh 根据 cluster-desc.yaml 选择下载CentOS还是CoreOS的images。
1. bsroot.sh 根据 cluster-dec.yaml 配置 PXE server 来网络启动 CentOS 还是 CoreOS。
1. 确认网络启动了OS之后，可以有办法自动安装OS到磁盘。
1. 确认为 CoreOSz 准备的 cloud-config 可以在 CentOS 上被执行。

**Comment by pineking** [comment]
是的，前四步已经验证可行性，CentOS 可以通过 PXE 自动安装到指定硬盘，后续可以细化后我提个 PR

目前主要是最后一步，在 CentOS 安装后验证如何实现正确运行 Cloud config

如果最后一步验证通过，我们就可以同时支持两个系统的全自动安装，👍👍👍
