### ISSUE TITLE
测试sextant pxe安装无法找到coreos_production_pxe.vmlinuz

### ISSUE THREAD

**Issue by JunfeiYang** [k8sp/sextant#380]
## 描述
安装完成bootstrapper后，启动master 无法找到coreos_production_pxe.vmlinuz
<img width="877" alt="2016-11-05 2 23 35" src="https://cloud.githubusercontent.com/assets/16366286/20028125/ec2603aa-a363-11e6-9ea7-398600c49d3d.png">
<img width="1255" alt="2016-11-05 2 32 32" src="https://cloud.githubusercontent.com/assets/16366286/20028154/c84d13dc-a364-11e6-871b-6fa37ba7ff6e.png">

**Comment by Yancey1989** [comment]
问题的原因是软链使用的是编译环境中的路径，编译环境不在bootstrapper的情况下，会导致找不到相应的文件，将链接路径修改为bootstrapper 机器上/bsroot下即可修复此问题。
