### ISSUE TITLE
如何实现两层次写文件

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#383]
在 `bsroot_centos.sh` 中有一个 `generate_provision_script` 函数，其作用是生成 CentOS 的安装配置文件是 `provision.sh`。而在 `provision.sh` 中，需要写 `docker.repo` 文件，这样就会存在两层次写文件的问题。

如果按照如下的格式写，运行 `bsroot_centos.sh` 时，会报 `EOF: command not found`

```bash
generate_provision_script() {
    printf "Generating provision script ... "
    mkdir -p $BSROOT/html/static/CentOS7
    cat > $BSROOT/html/static/CentOS7/provision.sh <<EOF
 #!/bin/bash

# Install Docker on CentOS
cat > /etc/yum.repos.d/docker.repo << EOF
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF

EOF

  echo "Done"
}
```

**Comment by pineking** [comment]
补充下上下文：

在 PXE 安装 CentOS时，`tftpboot/pxelinux.cfg/default` 中有如下一句话通过 kickstart 配置

**Comment by wangkuiyi** [comment]
The solution is here: http://stackoverflow.com/questions/13254077/is-nesting-of-here-document-possible-in-a-unix-bash-script

**Comment by pineking** [comment]
@wangkuiyi 我试了下，可以工作，赞！
