### ISSUE TITLE
合并 bsroot_centos.sh 到 bsroot.sh 中

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#389]
现状：
* 安装 CentOS 采用和安装 CoreOS 独立的 `bsroot_centos.sh` 脚本

需求：

* 建议根据 `cluster-desc.yaml` 读取安装 CentOS 或者 CoreOS 信息，合并 `bsroot_centos.sh` 到 `bsroot.sh` 中

**Comment by Yancey1989** [comment]
这个是不是可以先使用独立的bsroot_centos.sh 脚本将流程验证通过之后再做合并的事情？独立的脚本也比较好debug。

**Comment by pineking** [comment]
@Yancey1989 好的
