### ISSUE TITLE
在centos上搭建的k8s集群中，创建可访问gpu的pod时报错

### ISSUE THREAD

**Issue by xuerq** [k8sp/sextant#397]
error复现步骤：
1. 在包含gpu的节点上增加参数experimental-nvidia-gpus=1，重启kebelet
2. 在创建pod的yaml中，增加字段：
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
3. 启动pod失败，通过 kubectl describe pod {POD_NAME}命令，可看到如下log
{kubelet 0c-c4-7a-82-c5-bc}	spec.containers{worker}	Warning		Failed		Failed to start container with docker id aa5a0319488f with error: Error response from daemon: {"message":"linux runtime spec devices: **error gathering device information while adding custom device \"/dev/nvidia0\": lstat /dev/nvidia0: no such file or directory"**}

**Comment by pineking** [comment]
此问题已解决，原因在与集群的 /dev/nvidia* 不全，需要手工加载 nvidia-uvm.ko 驱动，然后 mkmod  /dev/nvidia-uvm

```bash
# Count the number of NVIDIA controllers found.
NVDEVS=`lspci | grep -i NVIDIA`
N3D=`echo "$NVDEVS" | grep "3D controller" | wc -l`
NVGA=`echo "$NVDEVS" | grep "VGA compatible controller" | wc -l`
N=`expr $N3D + $NVGA - 1`

for i in `seq 0 $N`; do
	mknod -m 666 /dev/nvidia$i c 195 $i
done

mknod -m 666 /dev/nvidiactl c 195 255

# Find out the major device number used by the nvidia-uvm driver
D=`grep nvidia-uvm /proc/devices | awk '{print $1}'`
mknod -m 666 /dev/nvidia-uvm c $D 0
```

* 执行 `nvidia-smi` 命令会自动创建 `/dev/nvidia*`，除了 `/dev/nvidia-uvm`
