### ISSUE TITLE
动态获取 IP 地址在 docker run ceph mon 中如何设置 MON_IP 和 CEPH_PUBLIC_NETWORK 的问题

### ISSUE THREAD

**Issue by jiamliang** [k8sp/sextant#406]
由于机群重的节点都是自动获取 IP 地址的，在 [install-mon.sh#49](https://github.com/k8sp/sextant/blob/develop/install-ceph/install-mon.sh#L49) 设置的 `-e MON_IP=$ip_addr` 和 `-e CEPH_PUBLIC_NETWORK=$net_mask` 这两个变量，其实是在 [install-mon.sh#L8~L10](https://github.com/k8sp/sextant/blob/develop/install-ceph/install-mon.sh#L8) 获取的，固定的 IP 地址和 net mask。 当这个机器节点的 IP 地址更换之后，很有可能就会出现问题。

尝试 1：
在 CentOS 中安装 ceph mon 的时候，将 MON_IP 设置为主机名 $(hostname) , CEPH_PUBLIC_NETWORK 设置为固定的 `10.10.15.0/24` ，在启动 ceph mon 的时候，会报告如下的错误：
``` shell
[root@00-25-90-c0-f7-7a ~]# docker restart ceph_mon; docker logs ceph_mon
ceph_mon
2016-11-17 11:52:16 /entrypoint.sh: key already exists
2016-11-17 11:52:17 /entrypoint.sh: Adding Mon Host - 00-25-90-c0-f7-7a
2016-11-17 11:52:17 /entrypoint.sh: No configuration found for cluster ceph-2. Generating.
2016-11-17T11:52:17Z 00-25-90-c0-f7-7a confd[90]: INFO Backend set to etcd
2016-11-17T11:52:17Z 00-25-90-c0-f7-7a confd[90]: INFO Starting confd
2016-11-17T11:52:17Z 00-25-90-c0-f7-7a confd[90]: INFO Backend nodes set to http://127.0.0.1:4001
2016-11-17T11:52:17Z 00-25-90-c0-f7-7a confd[90]: INFO Target config /etc/ceph/ceph-2.conf out of sync
2016-11-17T11:52:17Z 00-25-90-c0-f7-7a confd[90]: INFO Target config /etc/ceph/ceph-2.conf has been updated
2016-11-17 11:52:17 /entrypoint.sh: Creating Keyrings
creating /etc/ceph/ceph-2.client.admin.keyring
creating /etc/ceph/ceph-2.mon.keyring
creating /var/lib/ceph/bootstrap-osd/ceph-2.keyring
creating /var/lib/ceph/bootstrap-mds/ceph-2.keyring
creating /var/lib/ceph/bootstrap-rgw/ceph-2.keyring
2016-11-17 11:52:17 /entrypoint.sh: Creating Monmap
monmaptool: invalid ip:port '00-25-90-c0-f7-7a:6789'
```

尝试 2：
在 [entrypoint.sh#L211](https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L211) 中看到 NETWORK_AUTO_DETECT 这个环境变量，于是考虑通过设置这个环境变量，让 ceph mon 根据当时的 IP 自动进行设置：
 [install-mon.sh#49](https://github.com/k8sp/sextant/blob/develop/install-ceph/install-mon.sh#L49) 中去掉  `-e MON_IP=$ip_addr` 和 `-e CEPH_PUBLIC_NETWORK=$net_mask` 这两个变量， 增加 `-e NETWORK_AUTO_DETECT=1` ，然后重新执行 docker run， 虽然 ceph mon 并没有马上退出，在日志中看到，ceph mon 其实并没有处于正常的状态：
``` shell 
2016-11-17 22:01:32  /entrypoint.sh: Configuration is locked by another host. Waiting.
```
启动 ceph osd 的时候，通过 docker logs 查看到的日志是这样的：
``` shell
2016-11-18 02:02:18 /entrypoint.sh: OSD: Waiting for monitor setup to complete...
```
ceph mds 的日志和 ceph osd 的日志类似：
``` shell
2016-11-18 02:04:30 /entrypoint.sh: OSD: Waiting for monitor setup to complete...
```

解决思路：
1. NETWORK_AUTO_DETECT=1 这个方式需要研究一下，问题在哪里，如果能够搞定的话，就不会存在 IP 改变的问题了
2. 每次执行 docker run ceph mon 的时候（增加 --rm 参数），动态的获取到当前的 IP 地址，填进去。这个会不会有副作用，暂时未知。

**Comment by jiamliang** [comment]
2016-11-17 22:01:32  /entrypoint.sh: Configuration is locked by another host. Waiting.
 这个是因为 etcd 中有一个值 ：
``` shell
$ etcdctl get /ceph-config/ceph/lock 
00-25-90-c0-f7-7a
```
把这个删掉，就不会报告这个错误了。
但是新的问题出来了，正在查看。

**Comment by jiamliang** [comment]
``` shell
2016-11-18 09:11:26.717054 7fd3eacd24c0 -1 WARNING: 'mon addr' config option 10.10.15.20:0/0 does not match monmap file
         continuing with monmap configuration
```
导致 mon addr 配置信息不一致的原因是：之前在实验的时候遗留了错误的信息在 ETCD 中，并没有进行清除。 包括之前发现的：
``` shell 
2016-11-17 22:01:32 /entrypoint.sh: Configuration is locked by another host. Waiting.
``` 
这个也是 ETCD 旧数据没有清除导致的。

目前的解决办法比较暴力：删除掉 ETCD 中的信息，重新执行 populate_kvstore 操作。

**Comment by jiamliang** [comment]
总结一下：
解决 ceph mon 节点动态获取 IP 地址这种情况下 MON_IP 如何配置的问题，目前的解决办法是通过参数：NETWORK_AUTO_DETECT 来配置的。
在 [entrypoint.sh#L221](https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L221) 这部分代码中描述了 NETWORK_AUTO_DETECT 参数的意义：
NETWORK_AUTO_DETECT=1  ：先取 ipv6 的信息，取不到再取 ipv4 的信息
NETWORK_AUTO_DETECT=4  ：直接获取 ipv4 的信息
NETWORK_AUTO_DETECT=6  ：直接获取 ipv6 的信息

在使用了这个参数之后，我们就不需要再指定这两个参数： 
-e MON_IP=10.10.10.207 
-e CEPH_PUBLIC_NETWORK=10.10.10.207/24

``` shell
docker run -d --restart unless-stopped --net=host --name ceph_mon -v /etc/ceph/:/etc/ceph/ -v /var/lib/ceph/:/var/lib/ceph -e KV_TYPE=etcd -e CLUSTER=ceph-2 -e NETWORK_AUTO_DETECT=4  ceph/daemon mon;
```

**Comment by pineking** [comment]
@jiamliang 家盟有个问题啊，启用 `NETWORK_AUTO_DETECT=4` 后，在启动 ceph mon 的时候是不需要指定了，但是用户如果使用 ceph 的时候，如何指定 mon 机器？通过 mon 机器的 hostname 是可以的吧。
能否执行下 `ceph status` 看下 ceph 状态。

**Comment by jiamliang** [comment]
ceph status 的结果如下：
``` shell
root@00-25-90-c0-f7-c8:/# ceph status --cluster ceph-2
    cluster 7f6d4e2c-5855-486d-9bbf-451cac4b7f3b
     health HEALTH_OK
     monmap e3: 3 mons at {00-25-90-c0-f7-7a=10.10.15.20:6789/0,00-25-90-c0-f7-88=10.10.15.37:6789/0,00-25-90-c0-f7-c8=10.10.15.101:6789/0}
            election epoch 6, quorum 0,1,2 00-25-90-c0-f7-7a,00-25-90-c0-f7-88,00-25-90-c0-f7-c8
      fsmap e9: 1/1/1 up {0=mds-00-25-90-c0-f7-7a=up:active}, 2 up:standby
     osdmap e17: 3 osds: 3 up, 3 in
            flags sortbitwise
      pgmap v53: 80 pgs, 3 pools, 2068 bytes data, 20 objects
            101 MB used, 2778 GB / 2778 GB avail
                  80 active+clean
```

但是mount的时候，出问题了：
dmesg | tail  的结果如下：
```
[713934.158626] libceph: resolve '00-25-90-c0-f7-7a' (ret=-3): failed
[713934.158628] libceph: parse_ips bad ip '00-25-90-c0-f7-7a:6789'
```
域名解析有问题，不知道为什么，没有去253 上去解析 00-25-90-c0-f7-7a ；
在本机上解析  00-25-90-c0-f7-7a 是没有问题的：
```
liangjiameng@liangjiameng-Ubuntu:~$ nslookup 00-25-90-c0-f7-7a
Server:		10.10.15.253
Address:	10.10.15.253#53

Name:	00-25-90-c0-f7-7a
Address: 10.10.15.20
```

**Comment by jiamliang** [comment]
参考这篇文章 [MOUNT CEPH FS WITH THE KERNEL DRIVER](http://docs.ceph.com/docs/giant/cephfs/kernel/) 以及 [MOUNT.CEPH – MOUNT A CEPH FILE SYSTEM](http://docs.ceph.com/docs/master/man/8/mount.ceph/) 
还有这篇文章 [Ubuntu 14.04 - Mount Ceph Filesystem](sudo apt install ceph-common ceph-fs-common -y)

我按照下面这篇文章安装了：
```
sudo apt install ceph-common ceph-fs-common -y
```
就可以解决了。

如果不安装的话，使用IP也是可以 mount 的，这点官方文档提到了。

**Comment by LuPan2015** [comment]
@jiamliang  这个issue按照你上面的方法已经解决了是吧？

**Comment by jiamliang** [comment]
在安装 Ceph mon 之后，如果 mon 的 IP 发生了改变，仍需要人工介入处理。Ceph 不会自动地去改变 mon 的信息。可以通过设置 DHCP 的租约时间（永久？）来尽量避免 IP 被占用导致 IP 改变。
（副作用：IP 的租约时间越长，这个 IP 被回收的时间也就越长，如果有一台机器之前占用了这个 IP 但后来这台机器撤出来了，这个 IP 地址可能就很难被回收回来，给其他机器使用。）

**Comment by pineking** [comment]
@jiamliang 我们以后需不需要考虑加入固定和 DHCP 相结合的 IP 分配功能？
