### ISSUE TITLE
讨论：集群日常使用时，yum 源的设置

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#410]
讨论：集群日常使用时，如何设置集群中节点 yum 源

方案：

1. 节点能连外网，yum 源使用安装默认的 mirrors.centos.org，不做任何修改
2. 节点能连外网，yum 源通过 cluster-desc.yaml 设置为指定的外部 yum 源，比如 mirrors.163.com
3. 节点能连外网，yum 源通过 cluster-desc.yaml 设置为指定的外部 yum 源，比如 mirrors.163.com，和 bootstrapper server 上的内部 yum 源（**dvd.iso 源** + 部分自建源）
4. 节点能连外网，yum 源通过 cluster-desc.yaml 设置为指定的外部 yum 源，比如 mirrors.163.com，和 bootstrapper server 上的内部 yum 源（**dvd_everything.iso 源** + 部分自建源）
5. 节点不能连外网，yum 源通过 cluster-desc.yaml 设置为指定的 bootstrapper server 上的内部 yum 源（**dvd_everything.iso 源** + 部分自建源）

我觉得从 4 和 5 里选一种？

**Comment by pineking** [comment]
我选 4

**Comment by JunfeiYang** [comment]
我觉得选5比较合适一些。

**Comment by jiamliang** [comment]
4

**Comment by LuPan2015** [comment]
5
