### ISSUE TITLE
bsroot_lib.bash 解析 yaml 文件的时候，对数组的处理不恰当

### ISSUE THREAD

**Issue by jiamliang** [k8sp/sextant#412]
上下文：
在配置 etcd 的时候，需要获得所有 etcd member 的主机名（mac 地址），直接的处理方式是：解析 cluster-desc.yml 文件。
问题：
[bsroot_lib.bash](https://github.com/k8sp/sextant/blob/develop/scripts/bsroot_lib.bash)  中使用 load_yaml 来加载并解析 yaml 文件的时候，出现下面的情况：
yaml：
``` shell
nodes:
  - mac: "00:25:90:89:13:c6"
    ceph_monitor: y
    kube_master: y
    etcd_member: y
    ingress_label: n
  - mac: "00:25:90:89:13:cf"
    ceph_monitor: y
    kube_master: n
    etcd_member: y
    ingress_label: n
  - mac: "00:25:90:89:13:96"
    ceph_monitor: y
    kube_master: n
    etcd_member: y
    ingress_label: n
...
``` 
解析的结果：
![image](https://cloud.githubusercontent.com/assets/1405049/20507504/00b3c07a-b096-11e6-85a2-bc84f832cfcb.png)

``` shell
cluster_desc_nodes+=("mac: "00:25:90:89:13:c6"")
cluster_desc_nodes__ceph_monitor=("y")
cluster_desc_nodes__kube_master=("y")
cluster_desc_nodes__etcd_member=("y")
cluster_desc_nodes__ingress_label=("n")
cluster_desc_nodes+=("mac: "00:25:90:89:13:cf" ")
cluster_desc_nodes__ceph_monitor=("y")
cluster_desc_nodes__kube_master=("n")
cluster_desc_nodes__etcd_member=("y")
cluster_desc_nodes__ingress_label=("n")
cluster_desc_nodes+=("mac: "00:25:90:89:13:96"")
cluster_desc_nodes__ceph_monitor=("y")
cluster_desc_nodes__kube_master=("n")
cluster_desc_nodes__etcd_member=("y")
cluster_desc_nodes__ingress_label=("n")
```
最后的
``` shell
cluster_desc_nodes__ceph_monitor=("y")
cluster_desc_nodes__kube_master=("n")
cluster_desc_nodes__etcd_member=("y")
cluster_desc_nodes__ingress_label=("n")
```
会把前面其他 node 节点的信息给覆盖掉。

昨天找了一个类似的 bash 解析工具：
[parse_yaml2](https://gist.github.com/DinoChiesa/3e3c3866b51290f31243)

效果如下：
``` shell
cluster_desc_nodes+=("mac: "00:25:90:89:13:c6"")
cluster_desc_nodes__ceph_monitor+=("y")
cluster_desc_nodes__kube_master+=("y")
cluster_desc_nodes__etcd_member+=("y")
cluster_desc_nodes__ingress_label+=("n")
cluster_desc_nodes+=("mac: "00:25:90:89:13:cf" ")
cluster_desc_nodes__ceph_monitor+=("y")
cluster_desc_nodes__kube_master+=("n")
cluster_desc_nodes__etcd_member+=("y")
cluster_desc_nodes__ingress_label+=("n")
cluster_desc_nodes+=("mac: "00:25:90:89:13:96"")
cluster_desc_nodes__ceph_monitor+=("y")
cluster_desc_nodes__kube_master+=("n")
cluster_desc_nodes__etcd_member+=("y")
cluster_desc_nodes__ingress_label+=("n")
cluster_desc_ssh_authorized_keys=("|1+")
```
这个就要求，所有 node 节点下面的配置属性列表必须完全一致（比如说，所有的 node 节点必须都配置 ceph_monitor、kube_master、etcd_member、ingress_label），如果有中间的某一个节点不配置，就会错位。
这样的话，就可以通过 ${cluster_desc_nodes__ceph_monitor[i]} 来获取信息。这样处理还是比较麻烦的。

另外一个思路是：
直接访问 cloud-config-server 服务，获得 mac 地址对应的 cloud-config 文件，然后使用解析现成的 cloud-config 文件进行配置。【需要进一步验证可行性】

**Comment by pineking** [comment]
>另外一个思路是：
直接访问 cloud-config-server 服务，获得 mac 地址对应的 cloud-config 文件，然后使用解析现成的 cloud-config 文件进行配置。【需要进一步验证可行性】

解析现成的 cloud-config 文件是不是更麻烦？

**Comment by jiamliang** [comment]
解析 cloud-config 也是有问题的：
![image](https://cloud.githubusercontent.com/assets/1405049/20508063/e62aa26a-b099-11e6-85f0-1513c251380d.png)

**Comment by pineking** [comment]
我觉得第一种就可以，强制要求 node 属性格式一致，还是可以满足的。

另外一点，描述**直接粘相关文字或者代码**比较好，截图不容易看清楚，尤其是多窗口，不知道哪里是相关，除非比较简单的图

**Comment by jiamliang** [comment]
嗯，内容太多，担心格式乱。后面截图，我尽量隐藏无关窗口。
