### ISSUE TITLE
已经没必要从URL读取cluster-desc和cloud-config.template了

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/sextant#444]
目前看，从URL读取这两个文件的功能可以去掉了，请求cloud-config的请求压力不会很大，即时是100台机器的集群规模，所以没必要cache在内存。在bootstrapper启动的时候都是直接使用本地的文件。

当然cluster-desc的确有必要作为集群配置备份？应该使用何种方式

**Comment by pineking** [comment]
从 URL 读取 cluster-desc.yaml 和 cloud-config.template 是指什么？

**Comment by typhoonzero** [comment]
@pineking  之前有两个参数，可以制定github上的文件的url，然后cc server会下载并缓存到本地。

**Comment by pineking** [comment]
看到了，https://github.com/k8sp/sextant/blob/develop/docker/entrypoint.sh#L12
是 -cc-template-url 和 -cluster-desc-url 两个参数没必要了

顺便问下， https://github.com/k8sp/sextant/blob/develop/docker/entrypoint.sh#L15
cloud-config-server 传进去的 ca.pem 和 ca-key.pem 是作何用的？

**Comment by Yancey1989** [comment]
@pineking 当不指定根证书时会随机生成一份，有些场景是会使用公司自己的根证书。

**Comment by pineking** [comment]
@Yancey1989 cloud-config-server 用这证书做什么用途？

**Comment by Yancey1989** [comment]
worker节点和master的apiserver通信是需要经过TLS的双向认证的，而这些证书都是从根证书中生成出来的。 cloud-config-server指定这些证书是为了k8s节点获取cloud-config文件时，cloud-config-server把生成好的证书以write-files的方式写在cloud-config中。
参考：https://coreos.com/kubernetes/docs/latest/openssl.html

**Comment by pineking** [comment]
@Yancey1989 明白了，多谢!
