### ISSUE TITLE
CentOS 升级 kernel 版本变化较快

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#457]
目前 elrepo 最新的 kernel-ml 版本是 4.9.0 ，升级较快

为了解决这一问题
建议采用 kennel-lt，目前版本是 4.4.39 http://elrepo.org/linux/kernel/el7/x86_64/RPMS/
http://elrepo.org/tiki/tiki-index.php
http://elrepo.org/tiki/kernel-lt
 >The difference is that kernel-lt is based on a "long term support" branch and kernel-ml is based on the "mainline stable" branch.

最佳方案是通过 https://github.com/k8sp/sextant/issues/455 解决.

**Comment by typhoonzero** [comment]
有必要用4.4的kernel，为了能用overlayfs
