### ISSUE TITLE
bootstrapper服务器上安装和检查nginx

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#46]
我试着在一台Ubuntu虚拟机上和一台CentOS7虚拟机上安装Nginx。

## CentOS 7

CenOS 7 上的安装需要[两步](https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-centos-7):

1. sudo yum -y install epel-release
1. sudo yum -y install nginx

其中 `-y` 答题用户回答Yes。

## Ubuntu

Ubuntu 上安装 nginx 也用了两步：

1. sudo apt-get update
1. sudo apt-get install -y nginx

## 检查

在Ubuntu和CentOS 7上都是：安装之前不存在目录 /etc/nginx；之后有了 —— 验证了 @pineking 建议的检查方法。

**Comment by pineking** [comment]
@wangkuiyi 

CentOS 7 可以用 sudo yum --enablerepo=epel -y install nginx 一行命令

检查是否安装，除了check /etc/nginx 外，还可以
1. 检查/usr/sbin/nginx 可执行程序是否存在
2. 检查nginx服务是否存在，我们装完需要 systemctl或者service 启动nginx服务
CentOS 7: systemctl status nginx
Ubuntu 12.04: service nginx status

**Comment by wangkuiyi** [comment]
高！

根据你之前的建议，我在 https://github.com/k8sp/auto-install/pull/48 里修改了 cmd.go，让Cmd（现在改名叫Run了）打印信息，以便跟踪问题。
