### ISSUE TITLE
多余的代码

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#461]
cloud-config-server/template/cluster-desc.sample.yaml 中
```
# kube master ip, there should be cluster ip
kube_master_ip:
    - "10.100.0.1"
    - "192.168.61.73"
    - "192.168.48.23"
kube_master_dns:
    - "aa-bb-cc-dd"
```

这块代码是否是多余？没有必要

**Comment by JunfeiYang** [comment]
@pineking  经过查看这些代码下面配置使用：
<img width="977" alt="1" src="https://cloud.githubusercontent.com/assets/16366286/21375631/caa7006a-c769-11e6-83ef-8a43573aa5c8.png">
<img width="878" alt="2" src="https://cloud.githubusercontent.com/assets/16366286/21375632/cb1daf58-c769-11e6-9b45-f7b36f82515d.png">

**Comment by pineking** [comment]
经讨论，此处代码不多余

master IP 和 master DNS 用来生成证书，为了 ingress 或者 kubedns 能通过 master IP/DNS 访问
