### ISSUE TITLE
使用ThinkPad T440 作为worker节点 安装GPU驱动失败

### ISSUE THREAD

**Issue by JunfeiYang** [k8sp/sextant#472]
ThinkPad T440 作为worker节点 安装GPU驱动失败,经过检查发现以下问题：
1. pxe 网络安装时，wget 下载 build_centos_gpu_drivers.sh 成功，但是执行脚本失败；
2. /usr/local/bin/nvidia-gpu-mkdev.sh 没有发现。
<img width="734" alt="download-gpu" src="https://cloud.githubusercontent.com/assets/16366286/21559472/de3ea1ee-ce87-11e6-9218-cbcea9fbe79a.png">
<img width="1214" alt="gpu02" src="https://cloud.githubusercontent.com/assets/16366286/21559518/8f36c79c-ce88-11e6-8af3-ed6ac5a304d1.png">

**Comment by JunfeiYang** [comment]
@pineking 帮忙看看！

**Comment by pineking** [comment]
@JunfeiYang https://github.com/k8sp/sextant/blob/develop/bsroot.sh#L45 这一行执行了吗？

**Comment by JunfeiYang** [comment]
@pineking  执行了。在worker上已经可以下载到驱动了

**Comment by JunfeiYang** [comment]
经过排查，原因找到了，需要卸载内核自带的nv显卡驱动。编译既可以了。
