### ISSUE TITLE
docker 1.13.0 版本防火墙规则导致 pod 间互通有问题

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#525]
现状：
docker 1.13.0 版本的 pod 间以及外部访问 kubernetes 上的服务，比如 dashboard 存在被墙的现象.

原因：
docker 1.13.0 更改了默认的防火墙规整，FORWARD 改为了 drop，导致被防火墙 drop 了

参考描述：
https://github.com/kubernetes/kubernetes/issues/40182

解决方案：
方案一： 在所有节点上开机启动时执行 `sudo iptables -P FORWARD ACCEPT`
方案二：通过 docker.service 或者 /etc/docker/daemon.json 配置 dockerd 选项 --iptables=false

推荐方案二

**Comment by zh794390558** [comment]
在 ansible 中尝试 方案一。
