### ISSUE TITLE
是否将 kube-addons-manager 由 service 启动 docker 改为启动 binary

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#527]
目前的缺点：
* docker 方式启动，在 service restart 的时候，会导致多个 docker container 存在，原有的 container 依然 Up

如果改为 service 启动  binary 的 kube-addons-manager ，可避免此问题

**Comment by zh794390558** [comment]
是指 service restart 的时候并未将之前启动的 kube-adons-manger docker 干掉。然后又重新起了一个实例，造成多个实例的存在？
解决方法是将 docker 替换成 kube-addons-manger 的可执行程序？

**Comment by zh794390558** [comment]
解决方案： 在 kube-addons.service 中 rm 对应的 container。
