### ISSUE TITLE
在非PXE的环境下安装Kubernetes集群

### ISSUE THREAD

**Issue by Yancey0623** [k8sp/sextant#528]
在部署的时候，很多情况下基于一个已经安装好操作系统，DNS以及DHCP等服务的集群来部署Kubernetes。在这种情况下Sextant还不能实现自动化部署，我们是否要在`cluster-desc.yaml`增加一个类似`without_pxe`之类的参数来支持非PXE环境的自动安装。

下面是部分手动安装的步骤：
1. yum升级kernel
    http://linoxide.com/linux-how-to/upgrade-linux-kernel-stable-3-18-4-centos
    需要安装lt版(long term stable)
    ```bash
    rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm
    yum --enablerepo=elrepo-kernel install kernel-lt kernel-lt-devel
    ```
1. 设置kernel启动顺序
    ```bash
    cat /boot/grub2/grub.cfg|grep menuentry
    grub2-editenv list
    grub2-set-default "CentOS Linux (4.4.60-1.el7.elrepo.x86_64) 7 (Core)"
    http://forsk.blog.51cto.com/8096006/1841795
    ```
1. 安装NVIDIA显卡驱动
    ```bash
    wget -P /root http://10.252.20.11/static/CentOS7/gpu_drivers/build_centos_gpu_drivers.sh
    bash -x build_centos_gpu_drivers.sh 375.51 http://10.252.20.11/static/CentOS7/gpu_drivers/
    ```
1. 安装etcd flanneld等服务
    ```bash
    yum install -y etcd flannel cloud-init
    ```
1. 下载cloud-config file
下载后先修改POST_cloudinit_provision.sh中的bootstrapper_ip
    ```bash
    wget -P /root http://10.252.20.11/static/CentOS7/post_cloudinit_provision.sh
    bash -x post_cloudinit_provision.sh
    ```
1. Disable SELinux
    修改`/etc/selinux/config`中，`SELINUX=disabled`
1. 修改kubelet启动参数，使用systemd作为cgroup的driver
    ```bash
    --cgroup-driver=systemd
    ```

**Comment by pineking** [comment]
这个是我一直想写的，没有做

另外，第 7 个什么意思？在 PXE 安装的 kubelet 服务中 --cgroup-driver=systemd 这个参数设置不一样？

**Comment by zh794390558** [comment]
bash -x 是什么作用？

**Comment by Yancey0623** [comment]
> 在 PXE 安装的 kubelet 服务中 --cgroup-driver=systemd 这个参数设置不一样？

根据这个issue:https://github.com/kubernetes/kubernetes/issues/43805, 默认1.12版Docker和1.6kubelet使用的cgroup driver是不一致的。

@zh794390558 
>bash -x 是什么作用？ 

```
$man bash 
...
 -x file
    True if file exists and is executable.
```

**Comment by typhoonzero** [comment]
这个可以封装成一些工具脚本么？比如安装驱动和升级内核的一些事情。比如有一个脚本叫`sextant`，执行 `sextant upgrade-kernel-centos7`升级到最新的kernel，`sextant install nvidia-driver==371`安装指定版本的驱动等。。。

**Comment by zh794390558** [comment]
@Yancey1989 

>bash -x 是什么作用？
>$man bash 
>...
> -x file
>    True if file exists and is executable.

 应该是已 set -x 的方式执行对应的脚本文件。

**Comment by pineking** [comment]
推荐使用 ansible 实现
