### ISSUE TITLE
kube-addons 服务下载 yaml 文件改为 *.yaml 一次性匹配下载

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#548]
目前 kube-addons 下载 yaml 文件，是每个 yaml 文件 wget 单独下载
改为 *.yaml 一次性匹配下载比较简洁

**Comment by typhoonzero** [comment]
直接`*.yaml`貌似不行吧： https://github.com/k8sp/sextant/issues/545

**Comment by zh794390558** [comment]
@typhoonzero  是的，已经修正了。
