### ISSUE TITLE
Pack etcd3 flannel cloud-init tools to bsroot

### ISSUE THREAD

**Issue by typhoonzero** [k8sp/sextant#559]
Suppose we only have a cluster installed CentOS7, the installation ISO  mounted on each server, there's no internet access for all of the cluster servers.

So we need to pack etcd3 flannel cloud-init tools to bsroot. When doing an offline installation, The steps are:

1. Use `reposync --repoid=xxx --download_path=xxx`to download repos(like extras which contains cloud-init and docker), and pack them into bsroot.
1. Upload bsroot.tar.gz to bootstrapper server(one server in the cluster);
1. Setup yum to use local extras repo and install Docker on bootstrapper server;
1. Start bootstrapper.
1. Run installation script on each server using `yum install`;
1. Run bootstrap scripts like `post_cloudinit_provision.sh`.

Repos needed:

- extras: to install docker, cloud-init
- updates: which will be needed by extras
- ELRepo: to update kernel

Maybe we can also pack anything else and provide users an interface to deal with these tools.

**Comment by pineking** [comment]
现在的方式不满足需求吗？现在的方式是 bootstrapper 建了一个 local repo, 每台机器通过 yum安装 etcd cloud-init 等。

**Comment by typhoonzero** [comment]
Everything ISO中看起来并没有cloud-init这个包。`cloud-init`, `docker`都在extras里

**Comment by pineking** [comment]
cloud-init etcd 这些是在准备 bsroot 目录的时候下载的，准备 bsroot 目录的那台机器是有外网 internet 的权限

**Comment by typhoonzero** [comment]
是最近增加的功能么？我去看下代码先～
