### ISSUE TITLE
修改sextant适应企业内部环境

### ISSUE THREAD

**Issue by gongweibao** [k8sp/sextant#567]
Sextant设计之初考虑的是在裸机集群中一键式的解决方案。实际使用的过程中，企业内部的集群一般都有了自己的初始化安装环境，如部署了DHCP服务器，有自己的DNS，机器也有自己的hostname，机器之间通过hostname相互也能ping同。这种情况下，同时两个DHCP服务器无疑是有冲突的，需要对Sextant做一些改动以便适应这种的环境。

总体说来，Sextant=引导方式+资源的cache服务。各个节点软件的安装时通过kg(kickstart)文件安装，通过kg中调用post_script的方式配置和启动，通过ssh无密码登陆管理软件。

其中资源cache有下列部分:
- cloudinit源
- yum源
- docker registry
- GPU driver安装源

我们可以把Sextant PXE服务部分设置为可选项，保留资源cache服务部分。由于post_script不能通过kg的方式启动，所以引入[fabric](http://docs.fabfile.org/en/1.13/tutorial.html)作为集群管理者，方便安装、配置、检查、启动、关闭软件。

不能解决的问题：
- 不能升级系统的主版本，比如Centos6升级到Centos7，只可以做到升级内核。
   安装操作系统的基础版本还是一个繁琐的任务，当然，如果企业内部的PXE服务可以支持安装需要的基础版本是最好。

**Comment by pineking** [comment]
@gongweibao fabric 和 ansible 比如何？
关于 PXE 安装系统和 k8s 配置升级分开，我们搞了一个 dev_ansible 的分支，主要做了两件事情：
1. PXE 和 k8s 安装配置分开
2. ansible 简化原有 k8s 安装配置部分

**Comment by gongweibao** [comment]
hi， @pineking ，不好意思，回复的有点晚。主要是用的比较着急直接动手做了一些。
思路是这样的：
- 为了不冲突DHCP，所以加了一个`start_pxe`的选项，配置是否启动
- 为了兼容以前的伪mac地址当做hostname，在我们可能不能改动dns的情况下，把mac地址和ip的对应加入到了`/etc/hosts`文件中
- `upgrade kernel`和`install gpu driver`用fabric实现了一下，并且是分开的，因为后者的使用频率稍微大一些
- `install k8s`正在实现中，其实就是调用了一下`post_process.sh`和`post_cloudinit_provision.sh`两个脚本，并且准备加上check的功能，检查安装的是否准确。
    里边多加了一个配置文件，用来配置用户名，密码等，有些重复的是需要特殊配置的几个节点，需要把他们的mac地址和ip保存到各个机器的`/etc/hosts`中，不过为了解耦合，这样的重复配置其实还好。

fabric和ansible的对比还没有来得及做，fabric倒是很简单，只是现在还不能执行自定义的python函数。
也不清楚k8s的社区是否提供了ansible的支持？

**Comment by pineking** [comment]
>他们的mac地址和ip保存到各个机器的/etc/hosts中

IP 地址是 static 的？

**Comment by gongweibao** [comment]
目前的碰到的是啊。
主要是不想去改动sextant里边mac地址作为hostname的设计。

**Comment by pineking** [comment]
OK,明白了

**Comment by typhoonzero** [comment]
> upgrade kernel和install gpu driver用fabric实现了一下，并且是分开的，因为后者的使用频率稍微大一些

目前是把这两个操作和install k8s操作分开了么？

**Comment by gongweibao** [comment]
分开了。

**Comment by gongweibao** [comment]
@pineking 也帮忙review一下吧？https://github.com/k8sp/sextant/issues/566

**Comment by pineking** [comment]
@gongweibao Done
