### ISSUE TITLE
dnsmasq doesn't start

### ISSUE THREAD

**Issue by putcn** [k8sp/sextant#578]
I ran start_bootstrapper_container.sh, but in the container, there is no dnsmasq thread.

![screen shot 2017-09-27 at 11 09 11 pm](https://user-images.githubusercontent.com/2062926/30951632-ecca9b24-a3d8-11e7-8eb0-5c84b5d60474.png)

**Comment by putcn** [comment]
the command started entrypoint.sh is {entrypoint.sh} /bin/sh /entrypoint.sh **y**

**Comment by typhoonzero** [comment]
Can you please take a look at then contents of `entrypoint.sh`?

**Comment by putcn** [comment]
#!/bin/sh
```
if [[ $# != 1 ]]; then
    echo "need to set start_pxe"
    exit 1
fi

if [[ $1 == " y" ]]; then
    # start dnsmasq
    mkdir -p /bsroot/dnsmasq
    dnsmasq --log-facility=-  --conf-file=/bsroot/config/dnsmasq.conf \
      --dhcp-leasefile=/bsroot/dnsmasq/dnsmasq.leases
fi

# start cloud-config-server
/go/bin/cloud-config-server -addr ":80" \
  -dir /bsroot/html/static \
  -cloud-config-dir /bsroot/config/templatefiles \
  -cluster-desc /bsroot/config/cluster-desc.yml \
  -ca-crt /bsroot/tls/ca.pem \
  -ca-key /bsroot/tls/ca-key.pem &

# start registry
/go/bin/registry serve /bsroot/config/registry.yml &
sleep 2

wait
```

**Comment by typhoonzero** [comment]
Seems like dnsmasq got some error and exited, can you check out the log of the bootstrapper container and check if there's mis-configured lines in `dnsmasq.conf`?
