### ISSUE TITLE
不同版本系统对应的init systems

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#67]
1. System V is the older init system:
  Debian 6 and earlier
  Ubuntu 9.04 and earlier
  CentOS 5 and earlier
1. Upstart:
  Ubuntu 9.10 to Ubuntu 14.10, including Ubuntu 14.04
  CentOS 6
1. systemd is the init system for the most recent distributions featured here:
  Debian 7 and Debian 8
  Ubuntu 15.04 and newer
  CentOS 7

https://www.digitalocean.com/community/tutorials/how-to-configure-a-linux-service-to-start-automatically-after-a-crash-or-reboot-part-1-practical-examples

**Comment by jiamliang** [comment]
这个我知道，你的意思是针对不同的版本，进行调整？
centos 也有这个问题的

**Comment by pineking** [comment]
@jiamliang 我之前写了systemd 针对 CentOS 7， 还要写个 Upstart 针对 Ubuntu 14.04

**Comment by wangkuiyi** [comment]
@Yancey1989 @typhoonzero @LestDou @zhengbo0 百分点的机群里一般是什么操作系统？云知声是CentOS 7。我想如果百分点也是CentOS 7，那么bootstrapper是不是只需要支持CentOS 7 就好了？

**Comment by typhoonzero** [comment]
@wangkuiyi bootstrapper只需要CentOS7就好。可以单独使用一台CentOS7

**Comment by typhoonzero** [comment]
已经改成使用docker处理，如果后续有不使用docker启动的情况，再重新开启此issue
