### ISSUE TITLE
由于auto-install的方式改变，所以需要更改template的内容

### ISSUE THREAD

**Issue by LestDou** [k8sp/sextant#72]
目前https://github.com/k8sp/auto-install/blob/master/cloud-config-server/template/cloud-config.template 中的内容有一些说通过shell 脚本进行wget从外网获取zip包等方式进行安装。我们更倾向于通过配置文件加载，以service的方式进行，另外一些命令等二进制包可以直接通过bootstrapper上的nginx服务器进行提供。
另外对此修改也需要一些bootstrapper的功能上的支持，和对https://github.com/k8sp/auto-install/blob/master/cloud-config-server/template/unisound-ailab/build_config.yml  和 https://github.com/k8sp/auto-install/blob/master/cloud-config-server/template/template.go 进行一些修改和添加字段。
#53

**Comment by wangkuiyi** [comment]
@jiamliang @vienlee
