### ISSUE TITLE
bootstrapper: Kubenetes ACI images

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#82]

**Comment by vienlee** [comment]
CoreOS 上 `kubernetes` 通过 `/usr/lib/coreos/kubelet-wrapper` 中 rkt 启动 `hyperkube aci` 镜像启动, 因为服务节点多, 所以搭建内网 ACI 镜像
rkt fetch 镜像需要两个文件(有一定命名规范), aci(镜像) 和 asc(签名),  下面就通过创建内网 api 镜像并融合到kubelet.service 中去

1.` wget -O hyperkube:v1.2.4_coreos.cni.1 https://quay.io/c1/aci/quay.io/coreos/hyperkube/v1.2.4_coreos.cni.1/aci/linux/amd64/` 保存 `hyperkube:v1.2.4_coreos.cni.1` 镜像文件(得翻墙)
2. `curl -o hyperkube:v1.2.4_coreos.cni.1.aci.asc https://quay.io/c1/aci/quay.io/coreos/hyperkube/v1.2.4_coreos.cni.1/aci.asc/linux/amd64/` 保存 `hyperkube:v1.2.4_coreos.cni.1.aci.asc` 签名文件
3. 存放两个文件到 HTTP 服务器目录下, 得到访问 URL `http://10.10.10.192/hyperkube%3Av1.2.4_coreos.cni.1`
4. 修改 kubelet.service (这个文件通过安装脚本生成) 中的这两个参数
```
Environment=KUBELET_VERSION=v1.2.4_coreos.cni.1
Environment=KUBELET_ACI=http://10.10.10.192/hyperkube
```
5. 在已有服务集群上测试
```shell
# 停止 kubelet 服务
systemctl stop kubelet
# 删除原有 rkt 镜像
rkt image rm sha512-ba71ffc3aafd
# 删除 rkt pod
rkt rm 5a7cea21
# 初始化配置文件
systemctl daemon-reload
# 启动 kubelet 服务
systemctl start kubelet
# 查看服务日志
journalctl -fu kubelet
```

**Comment by Yancey1989** [comment]
LGTM. 我们也遇到了相同的问题，见issue：https://github.com/k8sp/auto-install/issues/28
除了ACI的Image，Docker Image也有同样的问题，我们在PXE Server上搭了一个Docker Registry用来存储pause,hyperkube等docker image。

**Comment by typhoonzero** [comment]
目前在使用aci还存在很多坑，比如：没有rkt stop命令(stable版本中)， rkt --dns没有作用等。目前的方法是志杰使用kubelet二进制来启动kubelet。参考master最新的cloud-config.template
