### ISSUE TITLE
docker 访问 ceph rbd 

### ISSUE THREAD

**Issue by pineking** [k8sp/sextant#84]
[by @wangkuiyi] 关于这个讨论的背景，在 https://github.com/k8sp/auto-install/issues/109

https://ceph.com/planet/getting-started-with-the-docker-rbd-volume-plugin/
http://www.sebastien-han.fr/blog/2015/08/17/getting-started-with-the-docker-rbd-volume-plugin/
http://www.atwop.com/archives/852.html

编译这个插件报错：

```
go get github.com/yp-engineering/rbd-docker-plugin

# github.com/yp-engineering/rbd-docker-plugin
../../../../yp-engineering/rbd-docker-plugin/main.go:83: cannot use d (type cephRBDVolumeDriver) as type volume.Driver in argument to volume.NewHandler:
        cephRBDVolumeDriver does not implement volume.Driver (missing Capabilities method)
```

**Comment by jiamliang** [comment]
rbd-docker-plugin 我也编译报错。
另外，官方的[README.md](https://github.com/yp-engineering/rbd-docker-plugin#ceph-rados-block-device-docker-volumedriver-plugin)文档说：
`an RBD Image can only be used by 1 Docker Container at a time`
这个是不是也不满足我们的需求？
我一会看一下另外那两个文档。

**Comment by pineking** [comment]
如果想手动在容器中map一个RBD image，通过已有的命令就可以实现，运行容器时需要提前把/dev和/sys挂载到容器内，详细教程可参考Ceph committer的文章 http://www.sebastien-han.fr/blog/2015/06/26/map-a-rbd-device-inside-a-docker-container/ 。而volume plugin只是通过API执行类似的操作，如果无须自动化也可以手动管理持久卷。

@jiamliang http://www.atwop.com/archives/852.html 家盟看看这个，手动挂载，作用和 plugin类似

**Comment by pineking** [comment]
@jiamliang  https://github.com/h0tbird/docker-volume-rbd

**Comment by jiamliang** [comment]
我们以后的实际使用场景是什么样的？不会在每一台物理机上mount ceph的image吧。
按照我的理解是，根据需要，在docker里面去挂载自己所需要的ceph image。比如说，ASR会挂载ASR的ceph image，TTS会挂载存储TTS数据的image。至于这些docker在那台物理机上运行，可能事先是不知道的，我们也没有必要把所有的ceph image都挂在在所有的物理机上。

**Comment by jiamliang** [comment]
rbd-docker-plugin issue [#41](https://github.com/yp-engineering/rbd-docker-plugin/issues/41)
回复：
`We don't (yet) support docker 1.10 nor the new volume-driver plugin "Capabilities" method.`

**Comment by wangkuiyi** [comment]
把 https://github.com/k8sp/auto-install/issues/85 里的内容（只贴了两个URL）挪到这里：
 
1. http://ceph.com/planet/bring-persistent-storage-for-your-containers-with-krbd-on-kubernetes/
1. http://www.atwop.com/archives/852.html

**Comment by typhoonzero** [comment]
已经完成：参考https://github.com/k8sp/sextant/blob/develop/install-ceph/README.md
