### ISSUE TITLE
全自动安装和配置Kubernetes机群

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/sextant#97]
我脑海里设想的流程和架构如下，请大家看看我们的理解是否是一致的，以及这样的设想是否有什么问题。

## 机群和网络

实际网络环境千差万别，为了让工作目标清晰可以执行，我建议我们只考虑以下网络情况，请大家看是否可以：

1. 若干node通过switch级联成一棵树。
1. 顶级swtich的upstream link接着一个[可翻墙的router](https://github.com/k8sp/coreos-cross-gfw/blob/master/chapter-1/transparent-router-cross-over-the-wall.md)，连接Internet。
1. 机群中有一个node，预先安装好了Ubuntu或者CentOS，并且在`/etc/network/interfaces`里写死了IP地址（static IP）。这台机器会是我们的bootstrapper server。
1. bootstrapper server上有DHCP服务，负责给机群中除了bootstrapper server之外的所有其他机器分配IP地址。

【讨论】我们的笔记本电脑怎么连接机群？如果要通过笔记本电脑ssh到bootstrapper server，是不是笔记本电脑也得是机群中的一员？

## IP地址、hostname 和 TLS crt

1. 机群中，除了bootstrapper server之外，有几台nodes是etcd cluster members。这些机器虽然也从DHCP服务获取IP，但是DHCP被bootstrapper程序配置为对这些nodes总是分配一个固定的IP（fixed IP）。这样其他机器上的etcd proxy进程可以明确知道etcd cluster member nodes的IP地址，从而加入etcd机群。

1. 除了 etcd members nodes，其他nodes的IP地址是完全动态分配的（dynamic IP）。

1. 每个node上有一个我们配置的服务，在node启动时，把node的IP地址和hostname写入bootstrapper server上的SkyDNS，这样我们就可以通过hostname来访问nodes了。

    1. hostname就是机器的primary NIC的MAC地址；

    1. 向SkyDNS注册很重要，因为每个node有自己独到的TLS key和crt，而生成crt是需要机器的域名（hostname）的。

【讨论】既然所有机器都会把自己的IP和hostname注册到SkyDNS里，是不是etcd cluster members就不需要fixed IP了，直接用他们的hostname就好了？

### 在笔记本电脑上

1. 获取或者生成 ca.key 和 ca.crt
1. `scp ca* bootstrapper-server:/`
1. `scp $GOPATH/bin/bootstrapper bootstrapper-server:/`
1. `ssh bootstrapper-server -c "sudo /bootstrapper -ca-key=/ca.key -ca-crt=/ca.crt`

### 在bootstrapper server上

`bootstrapper` 程序配置和启动各个服务，包括cloud-config-server：

```
cloud-config-server -ca-key=/ca.key -ca-crt=/ca.crt
```

这样，cloud-config-server也就有了CA，从而可以为每个node生成各自的crt。

### node加入机群

每台电脑买来的时候BIOS里默认的启动设备顺序是：硬盘优先，网络启动随后。这个默认顺序不需要修改，于是有以下流程：

1. 插电源线，插网线，按启动按钮。

1. 因为硬盘里没有操作系统，所以通过网络启动，向网络里广播DHCP请求。

1. bootstrapper server上的DHCP请求响应，返回一个IP地址（fixed IP或者dynamic IP），以及TFTP服务提供的pxelinux启动镜像的URL。

1. 新node获取镜像，启动系统，并且去TFTP上获取CoreOS启动镜像以及第一级cloud-config文件，引导到CoreOS，并且执行第一级cloud-config文件。

1. 第一级cloud-config文件其实是一个很短的shell script。也就是 https://github.com/k8sp/bootstrapper 里的 `install.sh`。

1. `install.sh`一方面访问bootstrapper server上的cloud-config-server，提供node的primary NIC的MAC地址，得到node的cloud-config文件（第二级cloud-config），这是一个YAML配置文件，
   1. cloud-config-server把node的MAC地址作为其hostname，从而为node生成crt。这个crt以及对应的key被嵌入在第二级cloud-config文件里返回给node。

1. 随后`install.sh`执行`coreos-install`脚本把CoreOS操作系统安装到本地磁盘，并且将第二级cloud-config文件配置为本地CoreOS启动时执行。

1. 最后`install.sh`重启node。

### node重启

1. 因为磁盘里有CoreOS了，所以这次不走网络启动，而是直接从磁盘启动。

1. 启动之后执行第二级cloud-config文件。

1. 第二级cloud-config文件里包含所有需要的配置信息，
   1. 配置etcd
   1. 配置Ceph
   1. 配置Kubernetes（包括flannel等）
   1. 配置一个服务，每次启动的时候把DHCP获得的IP地址和hostname（primary NIC MAC地址）注册到SkyDNS。

**Comment by pineking** [comment]
1.【讨论】我们的笔记本电脑怎么连接机群？如果要通过笔记本电脑ssh到bootstrapper server，是不是笔记本电脑也得是机群中的一员？
我觉得不需要是机群中的一员，静态路由或者双网卡应该可以搞定。

2.【讨论】既然所有机器都会把自己的IP和hostname注册到SkyDNS里，是不是etcd cluster members就不需要fixed IP了，直接用他们的hostname就好了？
这个说法有点问题，不是把IP和hostname注册到SkyDNS里，是把IP和hostname注册到etcd中，bootstrapper上起的skydns从etcd里获取各个机器的IP和hostname信息，提供DNS服务，所以我觉得还是需要fixed IP，skydns在启动的时候需要获得etcd member 的IP

3. node加入机群这段描述提到 “第一级cloud-config文件”， 我觉得这个容易引起误解，其实就是个coreos_install bash脚本，就叫 coreos_install.sh 好了，避免 第一级，第二级 cloud_config 的叫法引起问题

4. 顶级就可以翻墙，这个赞下，避免后面的一堆麻烦。

5. boostrapper 机器上的提供的功能能否用一小段介绍下，包括DHCP，nginx， skydns， PXE，以及提供cloud config 根据mac地址自动生成和下载

**Comment by wangkuiyi** [comment]
@pineking
